---
title: "Education, Intergenerational Mobility, and Poverty Dynamics"

categories:
  - Blog & commentary

date: 2023-06-19
#date-modified: today
date-format: "MMM YYYY"

author:
  - name: Olumide Taiwo
    affiliations:
      - ref: hdi
    attributes:
      corresponding: true
    email: otaiwo@helpmaninstitute.org
affiliations:
  - id: hdi
    name: Population Health Sciences, Helpman Development Institute, FCT Abuja, Nigeria.

format: 
  html: 
    fig-cap-location: margin
execute:
  echo: false
---

```{r setup, include=FALSE}
library(svglite)
library(flextable)
library(officer)
library(officedown)
knitr::opts_chunk$set(fig.width = 12, fig.height = 10, fig.align = "center",
                      out.width = "100%", collapse = TRUE, fig.pos = "H", out.extra = "",
                      ft.tabcolsep=5)
set_flextable_defaults(font.size = 10,
                       theme_fun = theme_booktabs,
                       table.layout = 'autofit',
                       font.family = "Arial")
```

# Model

We consider a closed overlapping-generations economy operating over an infinite discrete time horizon, starting with period 0. Individuals with perfect foresight invest in education and assets under capital market imperfection. However, the production of a single good occurs in a perfectly competitive environment where a single good produced can be consumed, invested, or passed on to the next generation. Population is exogenous and technology is assumed to be exogenous and stationary over time. Markets are imperfect in the sense that borrowing in the earlier periods of life for education acquisition is not possible. In particular, investment in education, which is apparently indivisible in this model, has to be financed out of savings of parents [^1]. In the adulthood (time $t$) each individual is allowed to invest, borrow, and/or lend at the market interest rate $R~t~$.

[^1]: Becker Gary S. and Nigel Tomes (1986), "Human Capital and the Rise and Fall of Families, *Journal of Labor Economics.* 4(3, part 2):S1-39.

## Producers

The amount of aggregate output produced in the adulthood (time $t$), $Y~t~$, is determined by the aggregate stock of physical capital at time $t$ (adulthood), $K~t~$, and the existing amount of efficient labor $N~t~$ --- where $N~t~$ is the amount of efficient labor---is defined as follows:[^2] (Rainer and Nardini, 2007)

[^2]: Andergassen Rainer and Franco Nardini (2007), "Educational Choice, Endogenous Inequality and Economic Development," *Journal of Macroeconomics*, 29, pp. 940 -- 958

$$
N~t = \lambda_tH_t^P + (1-\lambda_t)L_t^P \tag{1.1.1}\\    
$$

We assume that $\lambda_t \in (0,1)$, and $ρ≤1$. $H_t$ and $L_t$ are numbers of skilled and unskilled workers, respectively; where $H_t+L_t=Z_t$. At different stages of economic development, unskilled (skilled) workers might be relatively more abundant than skilled (unskilled) workers for aggregated production.

Following Rainer and Nardini (2007), we assume that skilled and unskilled workers are perfect substitutes if $ρ=1$, and perfect complements if $ρ=-∞$. Notice, however, that in Acemoglu (2002), the two inputs are referred to as gross substitutes if $0≤ρ<1$, and as gross complements if $ρ<1$. Let $φ_t$ be the ratio of the number of skilled workers to that of all workers $Z_t$. The aggregate supply of skilled workers at time t is $H_t=\phi_t Z_t$ and that of unskilled workers is $L_t=(1-φ_t)Z_t$.

The aggregate production function takes the Cobb-Douglas form:

$$
Y~t = AK_t^\alpha (N_t^\frac{1}{P})^{1-\alpha} \tag{1.1.2}\\     
$$

where $\alpha \in (0,1)$,and $A>0$ stands for the level of technology. The market price of the final good is normalized to 1.

Producers can freely rent the services of capital and labor from household through competitive factors markets. Hence, they maximize their profits given the market wages per unit of skilled and unskilled labors, $w_t^H,w_t^L$ and the rental price per unit of physical capital, $R_t$. Solving this problem is equivalent to choosing $H_t, L_t,and \:K_t$ that maximize $Y_t - w^HH_t - w_t^L L_t - r_t K_t$ subject to $Y~t = AK_t^\alpha (N_t^\frac{1}{P})^{1-\alpha}$ .The associated equilibrium wages of skilled and unskilled labors and the equilibrium price of physical capital are given by:

$$
w_L^H = (1 - \alpha) \lambda \frac{Y_t}{N_t} H_t^{p-1}    
$$

$$
w_L^H = (1 - \alpha) (1-\lambda) \frac{Y_t}{N_t} L_t^{p-1} \tag{1.1.3}\\     
$$

$$
q_t = \alpha \frac{Y_t}{K_t}
$$

## Households

### Environment

A new generation of individuals is born in each period, living over the course of two periods. The first period is divided between childhood and adulthood, while the last period coincides with old age or retirement. Since there is no decision process involved in the childhood, the economy will account for two generations at any point in time, namely adult and elderly persons. Individuals may be different in their initial wealth, yet they are homogeneous in all other aspects. The working population in each generation is $Z_t$, with a fraction $φ_t$ of the total population belonging to a group of skilled workers and a fraction $(1-φ_t)$ of the total population belonging to a group of unskilled workers. Hence, an individual born in period $t$ is referred to as a member of cohort $i$ of generation $t$, or simply a member $i$ of generation $t$.

Letting $\eta_t^i$ be an indicator function which takes a value of 1 when an individual invests in education and 0 if otherwise, and reiterating the fact that $w_t^H$ and $w_t^L$ are the wages of skilled and unskilled workers, respectively, the budget constraint in adulthood (time $t$) is given by the following equation:

$$
s_t^i = \eta_t^iw_t^H + (1 - \eta_t^i) w_t^L + (b_t^i - \eta_t^iP_t) \tag{1.2.1}\\   
$$

where $P_t$ indicates the cost of education for each individual during his young age, $s_t^i$ indicates savings made by an adult member of generation $t$. $(s_t^i = \eta_t^iw_t^H + (1 - \eta_t^i) w_t^L + (b_t^i - \eta_t^iP_t))$is the first period wealth after investment in education has occurred, that is, when $\eta_t^i=1$.

In the childhood, when young, each agent engages in skills acquisition. Investment in education is indivisible and is financed out of savings of parents; making poverty dynamics an issue in this model. Since a young agent is credit constrained when acquiring knowledge, education costs have to be covered out by parents through an intergenerational transfer (or bequest), $b_t^i$. If transfers from a parent is not enough to cover the entire cost of education, then there is no investment in education since capital markets are imperfect and there is no possibility for borrowing. However, if parental transfers exceed the cost of education, the excess is saved for the second period of life at the market interest rate $r_{t+1}$. Hence, investment in education is feasible only if transfers from parents are at least equal to the costs of acquiring education, that is, if

$$
b_t^i \ge P_t \tag{1.2.2}\\
$$

For simplicity's sake, we assume that the cost of education is proportional to total output. In particular, we set $P_t = pY_t$, where $p$ is the fraction of a household's income that is allocated to investment in education of the next generation.

It is important to note that invest in education is attractive only if the skill premium is larger than the costs of education, that is: $w_t^H-w_t^L≥P_t$. Using (1.1.3), we derive a condition under which it is optimal to invest in education:

$$
(\lambda H_t^{p-1} - (1-\lambda) L_t^{p-1}) \ge \frac {p}{1-\alpha} N_t \tag{1.2.3}\\   
$$

Equation (1.2.3) is associated with the well-known skill-premium condition where the left hand side (LHS) is the difference between skilled and unskilled workers' wages, and the right hand side (RHS) is the cost of investing in a child education.

In each generation, a member $i$ will use his/her savings for investment in real capital (economic capital) that can be sold to the final producer in period $t+1$ at price $q_{t+1}$, lend or borrow money at the same interest rate, $r_{t+1}$. The second period wealth of a member $i$ of generation $t$, $I_{t+1}^i$, depends on whether saving by a member $i$ of generation $t$, $s_t^i$, are sufficient to cover the costs of investment in real capital $k_t$. If $s_t^i < k_t$ the individual borrows the additional required funds in the first period of life, $(k_t - s_t^i)$ and repay the loan with interest rates in the second period. If, however, $s_t^i > k_t$ the individual finance the entire cost of investment in real capital and lend the excess funds, $(s_t^i - k_t)$ at the market interest rate. Hence, in the second period of life the individual wealth consists of interest on savings and income on real capital, i.e.,

$$
I_{t+1}^i = (s_t^i - k_t)r_{t+1} + q_{t+1}\phi^ik_t   
$$

Note that $\phi^i$ is the marginal productivity of each member $i$, with $\phi^i \in [\phi^L, \phi^H]$. Notice that a member $i$ of generation $t$ may choose not to invest in real capital if his productivity $\phi^i$ is below a certain threshold. As will become apparent in the next sections, the individual will only hold bonds and/or debts and become a net lender. In the second period his wealth will reduce to:

$$
I_{t+1}^i = r_{t+1}s_t^i   
$$

where $r_{t+1}$ is a market gross interest rate[^3].

[^3]: We assume internationally perfect capital mobility and a constant world interest rate such that $r_{t+1} = r_t = r$. Individuals are allowed to borrow or lend unlimited funds at this rate in the world market. In fact, the domestic interest rate is $r_t$, which is equal to the world interest rate $r$, i.e., $r_t = r$. International capital mobility implies therefore that the stock of physical capital employed in production, $K_t$ is constant overtime. (This assumption is not used for the time being)

As noted earlier, each member $i$ of generation $t$ can choose to start a project using his savings and borrowing from the bank. Following Kiminori Matsuyama (2002), the project comes in discrete, indivisible units and each member $i$ can only run one project[^4]. The project transforms $k_t$ units of the final good in period $t$ into $\phi^i k_t$ units of capital in period $t+1$. For the sake of exposition's simplicity, we focus on the case where

[^4]: Because of a continuum of agents that invest in the same project, the aggregate technology will remain convex even if each agent is facing an indivisible investment technology.

$$
s(\phi^ik_t) < k_t \tag{A.A.1}\\
$$

This assumption ensures that $s_t^i<k_t$, so that the agent needs to borrow $(k_t-s_t^i)>0$ in the competitive credit market, in order to start the project. The credit market is competitive in the sense that both lenders and borrowers take the equilibrium rate, $r_{t+1}$, as given. It is not competitive, however, in the sense that the bank imposes credit constraints on borrowers in order to avoid default. Knowing this, the bank will only commit to lend up to a certain fraction of his wealth, i.e.,

$$
d_t^i \ge -\mu k_t \tag{A.A.2}
$$

where $d_t^i \equiv (k_t-s_t^i)$ is negative and amounts to debt. As noted above, each member I of generation t can borrow from the bank up to $\mu$, $\mu>0$, times his wealth. As will become clear in the subsequent sections, the parameter $\mu$ is the index of financial development. When $\mu \rightarrow 0$, the financial market is nonexistent; both borrowing and lending are not possible. If however $\mu$ is large, the credit market is perfect and each member $i$ has the ability to borrow from the bank as much money as he requires.

The preferences of a member $i$ of generation $t$ are defined over consumption in the old age, $c_{t+1}^i$, and over the transfers to a child, $b_{t+1}^i$. They are represented by the log-linear utility function below:

$$
u(c_{t+1}^i, b_{t+1}^i) = (1-\beta) Inc_{t+1}^i + \beta In b_{t+1}^i   \tag{1.2.4}
$$

The underlying premise in (1.2.4) is that intergenerational transfers are luxury goods and are motivated by the "joy of giving".[^5]

[^5]: Using a utility function defined over the number of children (fertility) would not affect the qualitative results in this model. Hence we decide in favor of equation (1.2.5) for tractability's reasons.

Each member $i$ of generation $t$ faces budget constraints in the first and second periods as follows:

$$
d_t^i + k_t \le s_t^i \tag{1.2.5}
$$

$$
c_{t+1}^i \le q_{t+1} \phi^ik_t + r_{t+1}d_t^i - b_{t+1}^i\tag{1.2.6}
$$

A member $i$ of generation $t$ chooses his old age consumption,$c_{t+1}^i$, and a non-negative aggregate level of transfers to the offspring,$b_{t+1}^i$, so as to maximize the utility function in (1.2.4) subject to the constraints in (A.A.2), (1.2.5), and (1.2.6). In other terms the maximization can take the following form:

$$
Max_{(b_{t+1}^i,d_t^ik_t)} U = (1-\beta)In[q_{t+1}\phi^ik_t + d_t^ir_{t+1} -  b_{t+1}^i] + \beta In b_{t+1}^i
$$

subject to

$$
\left\{
  \begin{array}{ll}
        s_t^i = k_t + d_t^i \\
        d_t^i \ge-\mu k_t
    \end{array}
\right.
$$

We replace $d_t^i$ by $(s_t^i - K_t)$ in the above maximization, and we combine the two last constraints to obtain the following maximization problem:

$$
Max_{(b_{t+1}^i,d_t^ik_t)} U = (1-\beta)In[r_{t+1}+q_{t+1}[\phi^iq_{t+1} - r_{t+1}]k_t -  b_{t+1}^i] + \beta In b_{t+1}^i \tag{1.2.7}
$$

subject to

$$
0 \le k_t \le \frac {s_t^i}{1-\mu}
$$

**Assume that**

$$
\phi^i < (r_{t+1}/q_{t+1}) \equiv \Phi_t  \tag{A.A.3}
$$

no member i would invest in real capital[^6].In this case, $k_t=0$, and each member **I** hold his wealth in form of debt or bonds, i.e., $r_{t+1}d_t^i = r_{t+1}s_t^i = c_{t+1}^i + b_{t+1}^i$.

[^6]: In this case, the solution follows from the properties of the utility function and the nature of this maximization under capital market imperfections. Details will be given later

The rest of the demand functions will follow from first order conditions with respect to $c_{t+1}^i$ and $b_{t+1}^i$ are given below:

$$
b_{t+1}^i = \frac {\beta}{1-\beta}R_{t+1}q_t^i  \tag{1.2.8}
$$

Notice that $q_t^i$ = $w_t^H + (b_t^H -P_t)$ when $\eta_t^i = 1$, and $q_t^i = w_t^L + b_t^L$, when $\eta_t^i = 0$; with $b_t^H - P_t > 0$.

Following equations (1.2.1) and (1.2.5) we obtain the savings function below:

$$
s_t^i = \frac {1+\gamma - \beta} {1+\gamma} [(\eta_t^iw_t^H + (1- \eta_t^i )w_t^L + (b_t^i - \eta_t^iP_t))]  \tag{1.2.9}
$$

In this model, investment in education depends on the endowments for educated and uneducated cohorts. In order to properly deal with issues of poverty dynamics, we assume that skilled individuals remain skilled and unskilled individuals remain unskilled. $b_t^H$ indicates bequest (or transfers from skilled parents) of skilled individuals, i.e., $\eta_t^i=1$ for each $t$, and $b_t^L$ indicates bequest for unskilled individuals, i.e., $\eta_t^i=0$ for each $t$. In addition to the assumption that individuals within a cohort are homogeneous and remain as such, we also assume that:

$$
b_t^H \ge P_t > b_t^L \ge 0. \tag{A.A.4}
$$

Following equations (1.1.3), (1.2.8), and (1.1.1.), and assuming that $s_t^i>0$, we obtain that demand for education can be inferred from the choice variable for transfers from parents to offspring. Consequently, the dynamical equation for $b_t^H$ and $b_t^L$ are, respectively, given by:

$$
b_{t+1}^H = \alpha \nu \frac {\beta} {1-\beta} \tau [(1-\alpha)\lambda \frac {Y_t}{N_t} H_t^{p-1} + b_t^H - pY_t], \tag{1.2.10}\\   
$$

$$
b_{t+1}^L = \alpha \nu \frac {\beta} {1-\beta} \tau [(1-\alpha)(1-\lambda) \frac {Y_t}{N_t} L_t^{p-1} + b_t^L ], \tag{1.2.11}\\   
$$

where $\frac {Y_{t+1}} {k_{t+1}} \equiv \nu$. [^7] Equation (1.2.10) is the transfer from a skilled household of generation t, whereas, equation (1.2.11) is the transfer from an unskilled household of generation $t$.

[^7]: Well-known models of economic growth predict that the $Y-K$ ratio is constant in the long run. Recent models supporting this prediction include Solow (1956), Lucas (1988) and Romer (1986).

**Assume that**

$$
\Phi^i > (r_{t+1}/q_{t+1}) \equiv \Phi_t  \tag{A.A.5}
$$

The solution to (1.2.7) is now easy to deal with as the individual will invest as much as he can in the real capital; hence he will hold both real capital and debt in his portfolio:

$$
k_t = \frac {s_t^i} {1-\mu} \tag{1.2.12}
$$

$$
d_t^i = -  \frac {\mu} {1-\mu} s_t^i \tag{1.2.13}
$$

$$
b_{t+i}^i = \beta [q_{t+1} + \Phi^ik_t + r_{t+1}d_t^i ] \tag{1.2.14}
$$

Using (1.2.12) and (1.2.13) in (1.2.14), we find that

$$
b_{t+i}^i = \beta \frac {s_t^i}{1-\mu} [q_{t+1} + \Phi^i - \mu r_{t+1}] \tag{1.2.15}
$$

where $s_t^i = \eta_t^iw_t^H + (1-\eta_t^i)w_t^L + (b_t^i-\eta_t^iP_t)$, and \$ \frac {\\partial b\_{t+1}\^i}{\\partial\\mu} \> 0\$. $\mu$ is the index of the financial market development (or deepening). The last result in (1.1.15) indicates that intergenerational transfers for education purposes might depend on the level of development of financial market.

In the next pages we will make a simplifying assumption that $\phi^L \le (r_{t+1}/q_{t+1}) \equiv \Phi_t < \phi^H$.

The link between $b_{t+1}^H$ $(b_{t+1}^L)$ and $b_t^H$ $(b_t^L)$ is the most important relation for intergenerational dynamics of education and poverty. In particular,

$$
\Biggl(\frac {\partial b_{t+1}^H}{\partial b_{t}^H}, \frac {\partial b_{t+1}^L}{\partial b_t^L}\Biggl) >0 , \frac {\partial b_{t+1}^H}{\partial Y_{t}} >0 \Longleftrightarrow p < \frac {(1-\alpha)\lambda}{N_t}, \frac {\partial b_{t+1}^H}{\partial p} < 0. 
$$

In the absence of credit markets for investment in education, education costs have to be covered out of savings from parents,$b_t^i$, which is an intergenerational transfer (or bequest). Therefore, the regression model for investment in education is isomorphic to equation (1.2.10). In this regards, a simple formal function is derived from (1.2.10) as follows:

$$
e_{t+1} = \beta_0 + \beta_1e_t + \beta_2y_2 + \beta_3P_t+ \xi_i + u_i \tag{1.2.16}
$$

where $e_{t+1}$ indicates the level of education of the next generation, $e_t$ indicates the level of education of the current generation (parents), $\tau y_t$ is the costs of raising a child (it uses income per capita as proxy), $P_t$ is the cost of investing in human capital for one member of cohort H of generation $t$, $\xi _i$ reflects household unobserved characteristics, and $u_i$ is an error term.

# Bibliography

Andergassen Rainer and Franco Nardini (2007), "Educational Choice, Endogenous Inequality and Economic Development," *Journal of Macroeconomics*, 29, pp. 940 -- 958

Becker Gary S. and Nigel Tomes (1986), "*Human Capital and the Rise and Fall of Families, Journal of Labor Economics.* 4(3, part 2):S1-39.

Becker Gary S. (1979), "An Equilibrium theory of the Distribution of Income and Intergenerational Mobility."*Journal of Political Economy*, 87(6):1153-89.

Hyson Rosemary, (2003), "Differences in Intergenerational Mobility across the Earnings Distribution", *Working Paper 364*, BLS

Lucas E. Robert (1988), "On the Mechanics of Economic Development", *Journal of Monetary Economics* 22, pp 3-42.

Mulligan Casey B. "Parental Priorities and Economic Inequality;" *Chicago: University of Chicago Press*, 1997

Romer Paul M. (1986): "Increasing Returns and Long Run Growth," *Journal of Political Economy,* 94, 1002--37.

Solow Robert M. (1956), "A Contribution to the Theory of Economic Growth" *Quarterly Journal of Economics*, 70(1), pp. 65-94.
