---
title: "Unemployment and Wages in Less Developed Countries: Updating Harris-Todaro Model with Urban Informal Sector"
description: "Necessitating two main extensions to the Harris-Todoro's model that consider the urban informal sector, rural-urban migration, and wage comparisons, ultimately concluding that developing the urban informal sector is the most effective strategy to combat urban unemployment"
categories: 
  - Working papers

date: 2022-05-04
date-modified: today
date-format: "MMM YYYY"

author:
  - name: Olumide Taiwo
    affiliations:
      - ref: hdi
    attributes:
      corresponding: true
    email: otaiwo@helpmaninstitute.org

affiliations:
  - id: hdi
    name: Helpman Development Institute, Abuja, Nigeria.

format: 
  html: 
    fig-cap-location: margin

execute:
  echo: false
---

## Abstract

The Harris-Todaro's model of urban unemployment remains one of the historically insightful tools for analyzing urban unemployment problems in less developed countries (LDCs): a politically determined urban minimum wage set above rural agricultural wage draws rural workers into urban unemployment. Unfortunately, the urban informal sector that has become the largest employer of labor in the recent history of developing countries and its dynamics were largely underdeveloped at the time that the model was written. It is therefore not surprising that recent tests of the relationship between minimum wage and urban unemployment in different developing country settings demonstrate a failing of the model's prediction. In this paper, I make two main extensions to the model: I include an urban informal flexible-wage sector and allow for both rural-urban and urban-rural migration; and link rural wage to the size of rural labor. The urban sector is divided into the formal and the informal segments by the minimum wage and urban unemployment is driven by both rural-urban migrants and urban non-migrants. These extensions to the model yield three new insights: (1) an increase in minimum wage is not a precondition for rural-urban migration, (2) urban unemployment is driven largely by wage comparisons between the urban formal and informal sectors, and (3) urban unemployment is largely voluntary. The implication of the model is straightforward: the best strategy to reduce urban unemployment is to develop the urban informal sector. I discuss some policy choices.

## PDF links

-   [Paper (preprint) in PDF format](harris-todaro-model.pdf)
