---
title: "MAKING SENSE OF NIGERIA'S GROWING POPULATION"
format: html 
editor: visual
---

There is currently limited evidence, if any, to support the hysteria that emerged out of the first decade of the 21st century, of the prospective dividends of Africa's growing population, and especially of the youth cohorts. The Africa rising meme has since mellowed as a result of weakening economic growth, due primarily to falling commodity prices, and softening growth prospects.

Economic growth in the continent fell from average of 5.4% in 2000-2010 to 3.3% in 2010-2015 compared to global growth of 3.0% and 2.9% during the corresponding periods. The downward trend continued as growth in the region dropped further to 2.2% in 2016. Meanwhile, as population growth slowed in the rest of the world, Africa has continued to experience population boom. Projections indicate that Africa will account for about 60% of global population growth between 2017 and 2050 and be the main contributor to global population thereafter.

Nigeria maintains an outsize influence on the African population and economic growth trajectory. As shown below, the decline in Africa's economic growth from 3.9% in 2013 to 2.2% in 2016 reflects largely the decline in performance of the Nigeria economy from 5.5% growth in 2013 to 1.5% contraction in 2016. The influence is also noticeable in the projections through 2018 (Figure 1.1).

With population of 187 million in 2017, Nigeria is currently the 7^th^ most populous country and home to the fastest growing population in the world (2.7% per annum during 2010-2015). As a result, while Africa is recognized to have the youngest population among the world regions, Nigeria's population is even younger. Children under age 15 account for 44% of Nigeria's population compared to 41% in Africa, while the share of youths aged 15-19 remains the same at 19%. While a youthful population portends opportunities for demographic dividends, young children create additional burden of economic dependency that constrains potential dividends.

The economic benefits of population are dependent primarily on labor markets than any other market. That is, whether a growing population of working age becomes a net benefit or net burden depends primarily on the vibrancy of industry and commerce, and whether the labor force possesses the skills and human capital requirements of the sector.

In the absence of social safety nets, more specifically unemployment benefit programs, self-employment and entrepreneurship becomes the viable option for labor force participants unable to secure paid employment in government and organized private sector. Thus, in the absence of productive and competitive education and skills, hard and soft infrastructure essential for channeling financial resources to prospective entrepreneurs, and a friendly entrepreneurship sector, a growing population is essentially a ticking time bomb.

Although evidence shows that Nigeria is already within the demographic window of opportunity, a period during which population can yield substantial economic benefits if the conditions are right, there is no evidence that the country will generate positive demographic dividends under current conditions and the population and development experience.

The question on the minds of observers and analysts is how Nigeria can turn its growing population into a force for accelerated growth and development. Among other things, this will require changes in population structure and its geography, growth and productivity. The alternative is to maintain the status quo and look on as the population turns into an economic burden and breeding ground for social unrest, and ultimately a disaster.
