<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Usman Bala Usman">
<meta name="author" content="Dr.&nbsp;Olumide Taiwo">

<title>Helpman Institute - 
Exploring the Interplay between Education, Labor Market, and Fertility: A Study on FCT labor force</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Helpman Institute</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html" rel="" target="">
 <span class="menu-text">Research</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:info@helpmaninstitute.org" rel="" target=""><i class="bi bi-envelope" role="img" aria-label="email">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/company/helpmaninstitute" rel="" target=""><i class="bi bi-linkedin" role="img" aria-label="linkedin">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of Contents</h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#literature-review" id="toc-literature-review" class="nav-link" data-scroll-target="#literature-review"><span class="header-section-number">2</span> Literature review</a></li>
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology"><span class="header-section-number">3</span> Methodology</a>
  <ul class="collapse">
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">3.1</span> Data</a></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis"><span class="header-section-number">3.2</span> Analysis</a></li>
  </ul></li>
  <li><a href="#empirical-evidence" id="toc-empirical-evidence" class="nav-link" data-scroll-target="#empirical-evidence"><span class="header-section-number">4</span> Empirical evidence</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion"><span class="header-section-number">5</span> Discussion</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="education-labor-fertility.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><img src="resources/hdi_logo.png" class="img-fluid" style="width:2in"><br>
Exploring the Interplay between Education, Labor Market, and Fertility: A Study on FCT labor force</h1>
<p class="subtitle lead">Working paper</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Usman Bala Usman </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Helpman Development Institute, FCT Abuja, Nigeria.
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    <p class="author">Dr.&nbsp;Olumide Taiwo </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Helpman Development Institute, FCT Abuja, Nigeria.
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Jan 2024</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">May 2024</p>
    </div>
  </div>
    
  </div>
  

</header>

<div style="page-break-after: always;"></div>
<p><strong>ABSTRACT</strong></p>
<p><em>This research paper delves into the intricate interplay between education, labor, and fertility, unraveling nuanced relationships that shape family planning decisions using a multi-purpose survey conducted across major towns within the Federal Capital Territory (FCT) of Nigeria. Through a comprehensive analysis, the study reveals key findings: the negative impact of dependent children on intended fertility, the mitigating role of income, the complex dynamics of longer work hours, and the gender-specific influences of childhood household size. These findings contribute to our understanding of demographic transitions, shedding light on evolving societal structures and influencing policy considerations</em></p>
<p><strong>Key words</strong>: fertility, demographic transitions, labor, education, multi-purpose survey</p>
<div style="page-break-after: always;"></div>
<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>As societies undergo demographic transitions, the factors influencing family planning decisions become increasingly complex. Being able to untangle the web of relationships between education, labor, and fertility to provide valuable insights into contemporary reproductive attitudes remains a long-standing discussion (<span class="citation" data-cites="vignoli2020">Vignoli, Mencarini, and Alderotti (<a href="#ref-vignoli2020" role="doc-biblioref">2020</a>)</span>). It is the multifaceted nature of family planning, where economic considerations, work dynamics, and early-life experiences converge to shape fertility intentions that makes this an enthralling study. The effect of dependent children on intended fertility underscores the economic realities individuals face in the decision-making process (<span class="citation" data-cites="gomez2021">Gomez (<a href="#ref-gomez2021" role="doc-biblioref">2021</a>)</span>). In an era where financial stability is often a prerequisite for starting or expanding a family, understanding how the burden of dependent children influences fertility intentions is crucial for policymakers and researchers alike.</p>
<p>The thinking that income diminishes the possible negative effect of dependent children on intended fertility speaks to the role of economic empowerment in shaping family planning decisions (<span class="citation" data-cites="bonitsis1987">Bonitsis and Geithman (<a href="#ref-bonitsis1987" role="doc-biblioref">1987</a>)</span>). This emphasizes the need for comprehensive policies that address not only fertility preferences but also the economic conditions that underpin these preferences. One also has to factor in the effect of longer work hours on intended fertility, tempered by the effect of foster children, introducing a nuanced perspective. The substitution effect via the value of time helps to highlight the trade-off individuals face between career aspirations and family responsibilities. This has implications for workplace policies and the need for a balance that accommodates both professional and familial aspirations. Also, the distinct influences of childhood household size on fertility intentions among single and married individuals illuminate gender-specific dynamics. Understanding why one particular gender from a large childhood household might desire more children, in contrast to the lack of a similar effect among the other gender, provides insights into the enduring impact of early-life experiences on reproductive attitudes (<span class="citation" data-cites="balbo2011">Balbo and Mills (<a href="#ref-balbo2011" role="doc-biblioref">2011</a>)</span>).</p>
<p>Understanding the evolving nature of family planning decisions not only among single people but also within marital relationships is also pertinent for positive demographic transition. It will offer insights into the evolving nature of reproductive attitudes, the impact of economic conditions on family planning decisions, and the need for adaptable policies that consider the complexities of individual choices (<span class="citation" data-cites="safdari2023">Safdari-Dehcheshmeh et al. (<a href="#ref-safdari2023" role="doc-biblioref">2023</a>)</span>). As societies navigate demographic transitions, comprehending these factors becomes imperative for developing policies that align with the diverse and evolving aspirations of individuals and couples.</p>
</section>
<section id="literature-review" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Literature review</h1>
<p>The understanding of fertility behavior is a complex and multifaceted endeavor, delving into the intricate web of factors that influence individuals’ decisions regarding family size. It is pertinent to navigate through extensive research on intended fertility, shedding light on the interplay of economic, social, and gender-related factors that shape these decisions. Examining findings from various studies provides insights into the nuanced interplay of dependent children, income, work hours, childhood household size, and living costs on intended fertility. The myriad of factors shaping individuals’ decisions regarding family size and the dynamics between these factors need to be explored to have a good understanding of fertility behavior (<span class="citation" data-cites="aladeniyidemographic">Aladeniyi (<a href="#ref-aladeniyidemographic" role="doc-biblioref">n.d.</a>)</span>).</p>
<p>Child fostering introduces a dynamic element into the landscape of intended fertility, often leading to adjustments in family size. <span class="citation" data-cites="stewart2002">Stewart (<a href="#ref-stewart2002" role="doc-biblioref">2002</a>)</span> highlights the burden that arises from raising additional children, prompting individuals or couples to reevaluate their fertility intentions. As families expand, the perceived challenges and resource constraints associated with raising additional children often lead individuals or couples to revise their fertility intentions downward. The presence of foster children within a household emerges as a factor that may negatively influence couples’ childbearing intentions ( <span class="citation" data-cites="akresh2009">Akresh (<a href="#ref-akresh2009" role="doc-biblioref">2009</a>)</span>). <span class="citation" data-cites="akresh2009">Akresh (<a href="#ref-akresh2009" role="doc-biblioref">2009</a>)</span> findings suggest a nuanced relationship between fostering and fertility, indicating potential complexities that warrant deeper exploration.</p>
<p>However, the negative effect of foster children on intended fertility is not universal. The role of income in shaping fertility intentions is complex but critical. Higher-income levels generally provide families with the financial resources necessary to support additional children. Becker’s (1960) economic theory, conceptualizing children as “normal goods,” suggests that as income rises, the demand for children increases. In the context of foster children, higher income acts as a buffer, potentially easing the economic strain associated with expanding the family through fostering. The financial stability associated with higher income may diminish the perceived challenges of expanding the family, leading to a more positive outlook on intended fertility (Becker, 1969). Longer working hours are generally associated with delayed childbearing and lower fertility rates. However, there exists a nuanced relationship influenced by the substitution effect via the value of time. The interplay between work hours, income, and fertility decisions adds another layer of complexity to the understanding of intended fertility. Individuals, especially those with higher incomes, may value their time differently when contemplating family planning. High-income individuals often have the financial means to outsource childcare or hire domestic help, mitigating the time constraints linked to longer work hours. <span class="citation" data-cites="dotti2016">Dotti Sani and Treas (<a href="#ref-dotti2016" role="doc-biblioref">2016</a>)</span> corroborate this, illustrating that childcare time has increased more among the educated in many countries. The consideration of income as a moderating factor is crucial for unraveling the intricate relationship between work hours and fertility decisions, highlighting the need for nuanced analyses that account for economic disparities.</p>
<p>Childhood experiences also play a role in shaping fertility intentions. <span class="citation" data-cites="beaujouan2019">Beaujouan and Solaz (<a href="#ref-beaujouan2019" role="doc-biblioref">2019</a>)</span> emphasize that women, compared to men, who grew up in larger households may express a desire for more children, influenced by the positive experiences associated with a larger family structure. This suggests that gender differences and societal expectations may contribute to distinct influences on fertility intentions based on childhood household size. This gender-specific influence underscores the importance of recognizing the diverse pathways through which childhood experiences contribute to shaping fertility intentions (<span class="citation" data-cites="tanskanen2014">Tanskanen and Rotkirch (<a href="#ref-tanskanen2014" role="doc-biblioref">2014</a>)</span>). Previous literature offer a comprehensive overview of the factors influencing intended fertility, emphasizing the interconnectedness of economic, social, and gender-related dynamics. From child fostering to the impact of income on work hours and childhood experiences shaping gender-specific fertility aspirations, it is important to paint a rich tapestry of influences that converge to shape individuals’ decisions regarding family size. The economic landscape, societal norms, and gender roles all play pivotal roles in influencing how individuals and couples navigate the decision-making process regarding family size (<span class="citation" data-cites="duvander2020">Duvander et al. (<a href="#ref-duvander2020" role="doc-biblioref">2020</a>)</span>). The intricate interplay of these factors underscores the complexity of fertility choices and highlights the need for a holistic and intersectional approach in both research and policy formulation. As scholars continue to unravel the complexities within this domain, the knowledge generated can inform policies and interventions that respect the diversity inherent in fertility choices.</p>
</section>
<section id="methodology" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Methodology</h1>
<section id="data" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h2>
<p>In the pursuit of unraveling the intricate dynamics of intended fertility, a comprehensive multi-purpose survey was conducted across 10 major towns within the Federal Capital Territory (FCT) of Nigeria. The survey, executed from October 9th to October 24th, 2023 aimed to capture a diverse range of responses across various demographic groups. A structured questionnaire at individual level served as the primary tool for data collection. The choice of a structured questionnaire allowed for a systematic and standardized approach, ensuring consistency in data collection across the diverse sample. To ensure a robust representation of the population, a stratified sampling method was employed. Ten major towns within the FCT served as distinct strata, with samples drawn proportionally from each stratum. This approach aimed to account for potential variations in demographic characteristics and cultural nuances across different regions within the FCT.</p>
<p>A total of 842 individuals were interviewed during the survey period. Trained enumerators, equipped with a clear understanding of the survey’s objectives and methodologies, administered the questionnaires. The use of trained enumerators helped maintain consistency in the delivery of questions, minimized errors in data collection, and ensured a standardized approach to participant engagement. The questionnaire covered basic demographic information, labor market information and fertility intentions. Understanding these demographic factors was deemed crucial in contextualizing fertility intentions within the broader socio-demographic landscape.</p>
<p>The decision to conduct a primary data collection survey rather than relying on secondary data sources was deliberate, driven by several advantages. Firstly, primary data collection allowed for the customization of survey instruments to align with the specific nuances of the FCT’s diverse population. Tailoring questions to the local context ensured the relevance and cultural sensitivity of the survey, addressing factors that might not be adequately captured in existing secondary data sets. Secondly, primary data collection offered the opportunity to capture real-time and context-specific information. Fertility intentions, influenced by dynamic socio-cultural and economic factors, may experience shifts over time. By conducting the survey during a specific time frame, the research aimed to capture a snapshot of intended fertility dynamics, considering temporal variations that might be crucial for a comprehensive understanding. Moreover, primary data collection facilitated the inclusion of open-ended questions, enabling respondents to express their thoughts and experiences in their own words. This qualitative dimension added richness to the data, allowing for a deeper exploration of the complexities surrounding intended fertility.</p>
<p>Several unique aspects distinguish this survey from previous research endeavors. Firstly, the focus on 10 major towns within the FCT ensures a localized perspective, acknowledging the potential heterogeneity in fertility intentions within a specific geographical context. This geographical specificity allows for a nuanced analysis that considers regional variations, offering insights that might be overlooked in broader national surveys. The inclusion of trained enumerators also enhances the reliability of the data collected. The enumerators, equipped with a thorough understanding of the survey’s objectives, were able to address any clarifications required by participants, minimizing misunderstandings and ensuring a high level of data accuracy. Additionally, the emphasis on demographic factors, including age, gender, educational background, and income level, contributes to a holistic understanding of the context in which fertility intentions are formulated. Recognizing the interconnectedness of these demographic elements provides a comprehensive backdrop for interpreting the survey findings.</p>
</section>
<section id="analysis" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="analysis"><span class="header-section-number">3.2</span> Analysis</h2>
<p>Ordinary Least Squares (OLS) regression was used for the analysis, focusing on the intended number of children as the dependent variable. Respondents were asked about their plans for family size, providing a quantitative measure of their fertility intentions.</p>
<p><strong>Table 1:</strong> <strong>Pairwise correlation between variables</strong></p>
<table class="table">
<colgroup>
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 12%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td>Dependent Children</td>
<td>Monthly Income</td>
<td>Monthly living cost</td>
<td>Kids number currently</td>
<td>Number of intended children</td>
<td>Childhood household size</td>
<td>Hours worked in a week</td>
</tr>
<tr class="even">
<td>Number of Dependent Children</td>
<td>1.0000</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Monthly Income</td>
<td>0.0009</td>
<td>1.0000</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Monthly living cost</td>
<td>0.0421</td>
<td>0.7719*</td>
<td>1.0000</td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Kids number currently</td>
<td>0.2649*</td>
<td>0.2354*</td>
<td>0.2880*</td>
<td>1.0000</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Number of intended children</td>
<td>0.2887*</td>
<td>0.0574</td>
<td>0.0760*</td>
<td>0.3035*</td>
<td>1.0000</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Childhood household size</td>
<td>0.1797*</td>
<td>0.1013*</td>
<td>0.1243*</td>
<td>0.2564*</td>
<td>0.2972*</td>
<td>1.0000</td>
<td></td>
</tr>
<tr class="even">
<td>Hours worked in a week</td>
<td>0.0562</td>
<td>-0.2521*</td>
<td>-0.2120*</td>
<td>-0.0325</td>
<td>0.0206</td>
<td>0.0506</td>
<td>1.0000</td>
</tr>
<tr class="odd">
<td>Ideal number of children</td>
<td>0.2780*</td>
<td>0.0179</td>
<td>0.0016</td>
<td>0.2000*</td>
<td>0.7241*</td>
<td>0.2702*</td>
<td>0.0021</td>
</tr>
</tbody>
</table>
<p>The study explores various factors influencing family planning decisions, considering control variables and distinctive features of the surveyed population. Initially, the study considered the ideal number of children as an alternative dependent variable. However, a high correlation coefficient (0.72 as shown in Table 1) between the ideal and intended number of children led to the decision to focus solely on the intended number. The strong correlation indicated that respondents’ ideal and intended family sizes were closely aligned, making it difficult to distinguish between the two in the regression analysis.</p>
<p><strong>Table 2: Descriptive statistics of all respondents</strong></p>
<table class="table">
<colgroup>
<col style="width: 30%">
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 20%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<tbody>
<tr class="odd">
<td>Variable</td>
<td>Observations</td>
<td>Mean</td>
<td>Standard Deviation</td>
<td>Minimum</td>
<td>Maximum</td>
</tr>
<tr class="even">
<td>Number of Dependent children</td>
<td>839</td>
<td>0.3897</td>
<td>1.0543</td>
<td>0</td>
<td>8</td>
</tr>
<tr class="odd">
<td>Monthly income</td>
<td>694</td>
<td>131125</td>
<td>287655.4</td>
<td>10000</td>
<td>5000000</td>
</tr>
<tr class="even">
<td>Monthly living cost</td>
<td>838</td>
<td>106387.8</td>
<td>147616.6</td>
<td>10000</td>
<td>2000000</td>
</tr>
<tr class="odd">
<td>Kids number currently</td>
<td>841</td>
<td>1.1534</td>
<td>1.8038</td>
<td>0</td>
<td>10</td>
</tr>
<tr class="even">
<td>Number of intended children</td>
<td>839</td>
<td>4.2574</td>
<td>2.4152</td>
<td>0</td>
<td>20</td>
</tr>
<tr class="odd">
<td>Childhood household size</td>
<td>839</td>
<td>9.4219</td>
<td>5.1485</td>
<td>1</td>
<td>40</td>
</tr>
<tr class="even">
<td>Hours worked per week</td>
<td>726</td>
<td>51.0048</td>
<td>21.5859</td>
<td>0</td>
<td>140</td>
</tr>
</tbody>
</table>
<p>Approximately 18% of respondents reported having at least one foster child living with them. This distinctive aspect of the surveyed population introduces a variable that may influence the intended number of children. About 37% of respondents grew up in childhood households with more than 10 individuals. The experience of growing up in larger households could potentially shape individuals’ fertility intentions.</p>
<p><strong>Table 3: Descriptive statistics by gender</strong></p>
<table class="table">
<colgroup>
<col style="width: 23%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 18%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 18%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td><strong>MALE</strong></td>
<td></td>
<td></td>
<td><strong>FEMALE</strong></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><strong>Variable</strong></td>
<td><strong>Obs.</strong></td>
<td><strong>Mean</strong></td>
<td><strong>Standard deviation</strong></td>
<td><strong>Obs.</strong></td>
<td><strong>Mean</strong></td>
<td><strong>Standard deviation</strong></td>
</tr>
<tr class="odd">
<td>Hour worked per week</td>
<td>469</td>
<td>53.0954</td>
<td>23.3490</td>
<td>257</td>
<td>53.0954</td>
<td>17.3299</td>
</tr>
<tr class="even">
<td>Monthly income</td>
<td>453</td>
<td>155465.8</td>
<td>348712.7</td>
<td>241</td>
<td>155465.8</td>
<td>81812.58</td>
</tr>
<tr class="odd">
<td>Monthly living cost</td>
<td>541</td>
<td>116376.2</td>
<td>173335.9</td>
<td>297</td>
<td>116376.2</td>
<td>79312.78</td>
</tr>
<tr class="even">
<td>Number of intended children</td>
<td>542</td>
<td>4.6015</td>
<td>2.6828</td>
<td>297</td>
<td>4.6015</td>
<td>1.6576</td>
</tr>
<tr class="odd">
<td>Number of dependent children</td>
<td>542</td>
<td>0.4908</td>
<td>1.2095</td>
<td>297</td>
<td>0.4908</td>
<td>0.6485</td>
</tr>
<tr class="even">
<td>Kids number currently</td>
<td>544</td>
<td>1.2629</td>
<td>1.8762</td>
<td>297</td>
<td>1.2629</td>
<td>1.6474</td>
</tr>
<tr class="odd">
<td>Childhood household size</td>
<td>542</td>
<td>9.8432</td>
<td>5.6244</td>
<td>297</td>
<td>9.8432</td>
<td>4.0384</td>
</tr>
<tr class="even">
<td>Current household size</td>
<td>545</td>
<td>4.2459</td>
<td>3.0126</td>
<td>297</td>
<td>4.2459</td>
<td>2.7867</td>
</tr>
</tbody>
</table>
<div style="page-break-after: always;"></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure1.png" class="img-fluid figure-img" alt="Source: authors’ computation from survey data" width="560"></p>
<figcaption class="figure-caption">Monthly income/living cost by gender in FCT</figcaption>
</figure>
</div>
<p>The descriptive statistics in Table 3 offer valuable insights into the gender-specific dynamics of factors influencing fertility intentions. Variations in working hours, income, living costs, and family size preferences highlight the nuanced interplay of socioeconomic factors. Understanding these nuances is essential when considering the diverse influences on fertility decisions within different gender contexts.</p>
<p><strong>Table 4: Labor force statistics by gender</strong></p>
<table class="table">
<colgroup>
<col style="width: 30%">
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 14%">
<col style="width: 19%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td><strong>MALE</strong></td>
<td></td>
<td><strong>FEMALE</strong></td>
<td></td>
</tr>
<tr class="even">
<td><strong>Employment status</strong></td>
<td><strong>Mean monthly income</strong></td>
<td><strong>Mean hours of work per week</strong></td>
<td><strong>Mean monthly income</strong></td>
<td><strong>Mean hours of work per week</strong></td>
</tr>
<tr class="odd">
<td>Wage/Salary employee</td>
<td><p>106101.1</p>
<p>(164270.1)</p></td>
<td><p>53.5194</p>
<p>(24.4786)</p></td>
<td>80998.61 (64972.84)</td>
<td><p>53.5194</p>
<p>(24.4786)</p></td>
</tr>
<tr class="even">
<td>Employer (with at least 3 employees)</td>
<td><p>602702.7</p>
<p>(994628.3)</p></td>
<td><p>39.7576</p>
<p>(18.6397)</p></td>
<td>202000 (128724.5)</td>
<td><p>39.7576</p>
<p>(18.6397)</p></td>
</tr>
<tr class="odd">
<td>Self-employed (with maximum of 2 other persons)</td>
<td><p>138948.5</p>
<p>(171090.6)</p></td>
<td><p>55.9533</p>
<p>(21.2651)</p></td>
<td>87692.31 (89933.06)</td>
<td><p>55.9533</p>
<p>(21.2651)</p></td>
</tr>
<tr class="even">
<td>Family enterprise (without standard contract/wages)</td>
<td><p>69230.77</p>
<p>(53496.35)</p></td>
<td>69230.77 (53496.35)</td>
<td><p>46.2</p>
<p>(22.3645)</p></td>
<td><p>46.2</p>
<p>(22.3645)</p></td>
</tr>
</tbody>
</table>
<p><em>Standard deviations in parentheses</em></p>
<p>The employment status of individuals plays a significant role in shaping fertility intentions, reflecting the intricate interplay between income, working hours, and the ability to balance work and family life (Table 4). The potential financial success of entrepreneurship can positively impact fertility intentions, but it may also introduce complexities in managing time and responsibilities. Self-employed individuals and employers may experience unique challenges in balancing the demands of entrepreneurship with family aspirations. Addressing challenges related to work-life balance, income disparities, and the unique circumstances of different employment categories can contribute to a more comprehensive understanding of the factors influencing fertility intentions in diverse socio-economic contexts.</p>
<p>To ensure a comprehensive analysis, several control variables such as gender, marital status, education level, age and religion were included in the regression model. A binary variable (1 for female, 0 for male) was used to account for potential gender-related differences, while a categorical variable accounting for single, married, divorced, or widowed respondents was used in the aspect of marital status.</p>
<p>For married individuals, an additional control variable, the current number of children, was introduced in the regression analysis. The current number of children which is the summation of an individual’s biological children and adopted children, helped to provide insights into the existing family structure.</p>
</section>
</section>
<section id="empirical-evidence" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Empirical evidence</h1>
<p>Table 5: Factors influencing intended fertility among single individuals</p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<tbody>
<tr class="odd">
<td>Variables</td>
<td>Model 1</td>
<td>Model 2</td>
<td>Model 3</td>
<td>Model 4</td>
<td>Model 5</td>
</tr>
<tr class="even">
<td>Log monthly income</td>
<td><p>-0.0245</p>
<p>(0.1320)</p></td>
<td><p>-0.1390</p>
<p>(0.1360)</p></td>
<td><p>-0.1310</p>
<p>(0.1360)</p></td>
<td><p>-0.5280**</p>
<p>(0.2600)</p></td>
<td><p>-0.5070*</p>
<p>(0.2610)</p></td>
</tr>
<tr class="odd">
<td>Hours worked per week</td>
<td><p>0.0076*</p>
<p>(0.0043)</p></td>
<td><p>0.00834**</p>
<p>(0.0042)</p></td>
<td><p>0.0105**</p>
<p>(0.0044)</p></td>
<td><p>0.0097**</p>
<p>(0.0044)</p></td>
<td><p>0.0059</p>
<p>(0.0068)</p></td>
</tr>
<tr class="even">
<td>Childhood household size</td>
<td><p>0.0503**</p>
<p>(0.0222)</p></td>
<td><p>0.0444**</p>
<p>(0.0220)</p></td>
<td><p>0.0453**</p>
<p>(0.0220)</p></td>
<td><p>-0.4280</p>
<p>(0.2650)</p></td>
<td><p>-0.4180</p>
<p>(0.2650)</p></td>
</tr>
<tr class="odd">
<td>Number of dependent children</td>
<td><p>0.2500**</p>
<p>(0.1240)</p></td>
<td><p>-5.6220***</p>
<p>(1.9500)</p></td>
<td><p>-4.3520**</p>
<p>(2.0730)</p></td>
<td><p>-4.6080**</p>
<p>(2.0720)</p></td>
<td><p>-4.6430**</p>
<p>(2.0740)</p></td>
</tr>
<tr class="even">
<td>Income × Dependent</td>
<td></td>
<td><p>0.5460***</p>
<p>(0.1810)</p></td>
<td><p>0.4790***</p>
<p>(0.1850)</p></td>
<td><p>0.4960***</p>
<p>(0.1840)</p></td>
<td><p>0.5020***</p>
<p>0.1850)</p></td>
</tr>
<tr class="odd">
<td>Hours worked × Dependent</td>
<td></td>
<td></td>
<td><p>-0.0085*</p>
<p>(0.0048)</p></td>
<td><p>-0.0073</p>
<p>(0.0048)</p></td>
<td><p>-0.0077</p>
<p>(0.0049)</p></td>
</tr>
<tr class="even">
<td>Income × Childhood</td>
<td></td>
<td></td>
<td></td>
<td><p>0.0422*</p>
<p>(0.0236)</p></td>
<td><p>0.0391</p>
<p>(0.0240)</p></td>
</tr>
<tr class="odd">
<td>Hours worked × Childhood</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td><p>0.0004</p>
<p>(0.0005)</p></td>
</tr>
<tr class="even">
<td>Constant</td>
<td><p>1.8000</p>
<p>(1.7740)</p></td>
<td><p>3.0990*</p>
<p>(1.8080)</p></td>
<td><p>2.8090</p>
<p>(1.8100)</p></td>
<td><p>7.2030**</p>
<p>(3.0440)</p></td>
<td><p>7.2640**</p>
<p>(3.0470)</p></td>
</tr>
<tr class="odd">
<td>Observations</td>
<td>394</td>
<td>394</td>
<td>394</td>
<td>394</td>
<td>394</td>
</tr>
<tr class="even">
<td>R-squared</td>
<td>0.2230</td>
<td>0.2410</td>
<td>0.2480</td>
<td>0.2540</td>
<td>0.2550</td>
</tr>
</tbody>
</table>
<p><em>Standard errors in parentheses - [*** p&lt;0.01, ** p&lt;0.05, * p&lt;0.1]</em></p>
<p><em>Model 1 is a regression analysis without any interaction terms, while Model 2 includes an interaction term between monthly income and number of dependent children. Model 3 includes the hours worked and number of dependent children interaction term while Model 4 includes the monthly income and childhood household size interaction term. Model 5 includes interaction terms between monthly income, hours worked weekly, number of dependent children and childhood household size. Other controls are age, educational level, religion and work location</em></p>
<p>Table 5 explores the factors influencing intended fertility among aggregate singles. The coefficients for hours worked per week are consistently positive and statistically significant, especially in Models 2, 3, and 4. This indicates that individuals who work longer hours per week tend to express a higher intention to have children. This positive relationship suggests that employment or a busy work schedule may influence individuals to delay family planning or express a desire for fewer children, highlighting the complex interplay between employment and fertility decisions. The coefficients for childhood household size are consistently positive and statistically significant in Models 1, 2, and 3. This suggests that individuals who grew up in larger households tend to express a higher intention to have children. This finding is in line with the notion that family size during childhood may influence one’s own fertility intentions later in life. Larger families during childhood may contribute to a positive attitude towards having more children. The coefficients for dependent Children are consistently negative and highly significant across all columns indicating that individuals with dependent children express a lower intention to have more children. The negative impact of dependent children on fertility intentions is intuitive – individuals with existing childcare responsibilities may be inclined to plan for a smaller family size.</p>
<p>The positive coefficients for the income and dependent children interaction term suggest that income mitigates the negative impact of having dependent children on fertility intentions. In other words, higher income levels help counterbalance the tendency of individuals with dependent children to express a lower intention to have more children. This underscores the role of economic factors in shaping fertility decisions, particularly in the context of existing family responsibilities. The negative coefficients for the hours worked and dependent children interaction term suggest that the presence of dependent children reduces the positive impact of working longer hours on fertility intentions. This implies that the demands of both work and childcare may lead to a moderation in fertility intentions. Balancing work and family responsibilities appears to influence fertility decisions.</p>
<p>The R-squared values for Table 5 increase across columns, indicating an improvement in the model’s explanatory power. The interaction terms reveal the nuanced ways in which income and work hours interact with other factors to influence fertility intentions. Higher income levels may provide a buffer against the negative impact of dependent children, while the combination of a busy work schedule and a larger childhood household may jointly contribute to a higher intention to have more children.</p>
<p><strong>Table 6: Factors influencing intended fertility among single men</strong></p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<tbody>
<tr class="odd">
<td>Variables</td>
<td>Model 1</td>
<td>Model 2</td>
<td>Model 3</td>
<td>Model 4</td>
<td>Model 5</td>
</tr>
<tr class="even">
<td>Log monthly income</td>
<td><p>0.0269</p>
<p>(0.1570)</p></td>
<td><p>-0.0934</p>
<p>(0.1630)</p></td>
<td><p>-0.0893</p>
<p>(0.1620)</p></td>
<td><p>-0.7240**</p>
<p>(0.3030)</p></td>
<td><p>-0.6970**</p>
<p>(0.3060)</p></td>
</tr>
<tr class="odd">
<td>Hours worked per week</td>
<td><p>0.0056</p>
<p>(0.0052)</p></td>
<td><p>0.0066</p>
<p>(0.0051)</p></td>
<td><p>0.0096*</p>
<p>(0.0053)</p></td>
<td><p>0.0087*</p>
<p>(0.0052)</p></td>
<td><p>0.0050</p>
<p>(0.0081)</p></td>
</tr>
<tr class="even">
<td>Childhood household size</td>
<td><p>0.0300</p>
<p>(0.0255)</p></td>
<td><p>0.0251</p>
<p>(0.0253)</p></td>
<td><p>0.0272</p>
<p>(0.0252)</p></td>
<td><p>-0.6890**</p>
<p>(0.2910)</p></td>
<td><p>-0.6760**</p>
<p>(0.2920)</p></td>
</tr>
<tr class="odd">
<td>Number of dependent children</td>
<td><p>0.4480***</p>
<p>(0.1510)</p></td>
<td><p>-5.0630**</p>
<p>(2.2790)</p></td>
<td><p>-3.2970</p>
<p>(2.4150)</p></td>
<td><p>-3.9020</p>
<p>(2.4010)</p></td>
<td><p>-3.9350</p>
<p>(2.4040)</p></td>
</tr>
<tr class="even">
<td>Income × Dependent</td>
<td></td>
<td><p>0.5070**</p>
<p>(0.2090)</p></td>
<td><p>0.4100*</p>
<p>(0.2130)</p></td>
<td><p>0.4560**</p>
<p>(0.2110)</p></td>
<td><p>0.4610**</p>
<p>(0.2120)</p></td>
</tr>
<tr class="odd">
<td>Hours worked × Dependent</td>
<td></td>
<td></td>
<td><p>-0.0110**</p>
<p>(0.0052)</p></td>
<td><p>-0.0090*</p>
<p>(0.0053)</p></td>
<td><p>-0.0094*</p>
<p>(0.0053)</p></td>
</tr>
<tr class="even">
<td>Income × Childhood</td>
<td></td>
<td></td>
<td></td>
<td><p>0.0635**</p>
<p>(0.0257)</p></td>
<td><p>0.0602**</p>
<p>(0.0263)</p></td>
</tr>
<tr class="odd">
<td>Hours worked × Childhood</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td><p>0.0003</p>
<p>(0.0005)</p></td>
</tr>
<tr class="even">
<td>Constant</td>
<td><p>1.1980</p>
<p>(2.0310)</p></td>
<td><p>2.4970</p>
<p>(2.0800)</p></td>
<td><p>2.1700</p>
<p>(2.0800)</p></td>
<td><p>9.1890***</p>
<p>(3.5010)</p></td>
<td><p>9.2010***</p>
<p>(3.5060)</p></td>
</tr>
<tr class="odd">
<td>Observations</td>
<td>245</td>
<td>245</td>
<td>245</td>
<td>245</td>
<td>245</td>
</tr>
<tr class="even">
<td>R-squared</td>
<td>0.2900</td>
<td>0.3080</td>
<td>0.3210</td>
<td>0.3390</td>
<td>0.3400</td>
</tr>
</tbody>
</table>
<p><em>Standard errors in parentheses</em></p>
<p><em>*** p&lt;0.01, ** p&lt;0.05, * p&lt;0.1</em></p>
<p><em>Other controls are age, educational level, religion and work location</em></p>
<p>Table 6 explores the factors influencing intended fertility among single men. The coefficients for log-transformed monthly income are consistently negative across all columns, with statistical significance in Models 4 and 5. This suggests that an increase in log-transformed monthly income is associated with a decrease in the intended number of children among single men. The negative impact of income on fertility aligns with patterns observed in demographic transitions, where higher income is often associated with lower fertility rates. The coefficients for hours worked per week are consistently positive and statistically significant across Models 3, 4, and 5. This indicates that, for single men, working longer hours per week is associated with a higher intention to have children. The positive relationship between working hours and fertility intentions highlights the potential impact of career demands or personal preferences on family planning decisions among single men.</p>
<p>In contrast to the findings for aggregate singles, the coefficients for childhood household size are consistently positive in Models 1, 2, and 3 for single men. However, these coefficients become negative and statistically significant in Models 4 and 5. This suggests that, among single men, a larger childhood household size is associated with a higher initial intention to have children, but this effect diminishes and becomes negative in the presence of other factors.</p>
<p>In Table 6 also, the coefficients for dependent children are consistently negative across all models, indicating that the presence of dependent children is associated with a lower intention to have more children among single men. This aligns with the notion that existing childcare responsibilities may lead to a desire for a smaller family size among single men.</p>
<p>The positive coefficients for the income and dependent children interaction term in Table 6 suggest that income mitigates the negative impact of having dependent children on fertility intentions among single men. Higher-income levels seem to counterbalance the tendency of single men with dependent children to express a lower intention to have more children. The negative coefficients for the hours worked and dependent children interaction term suggest that the presence of dependent children reduces the positive impact of working longer hours on fertility intentions among single men. This finding implies that the demands of both work and childcare may jointly contribute to a moderation in fertility intentions among single men.</p>
<p>The positive coefficients for the income and childhood household interaction term suggest that income enhances the positive impact of childhood household size on fertility intentions among single men. This finding indicates that higher income levels may amplify the influence of a larger childhood household on an individual’s intention to have more children.</p>
<p>The results in Table 6 offer insights into the factors shaping fertility intentions among single men, providing nuances to the broader understanding of demographic transitions. The negative impact of income on fertility aligns with the idea that economic stability and career focus may influence family planning decisions among single individuals.The dynamics related to childhood household size highlight the complexity of factors influencing fertility intentions among single men. The initial positive impact of childhood household size on fertility intentions may reflect cultural or familial influences, but its diminishing effect in the presence of other factors underscores the importance of considering a holistic set of variables. The negative impact of dependent children on fertility intentions emphasizes the role of existing parental responsibilities in shaping family planning decisions among single men. The moderating effects of income and working hours on this relationship highlight the intricate interplay between economic factors, career considerations, and family planning.</p>
<p><strong>Table 7: Factors influencing intended fertility among single women</strong></p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<tbody>
<tr class="odd">
<td>Variables</td>
<td>Model 1</td>
<td>Model 2</td>
<td>Model 3</td>
<td>Model 4</td>
<td>Model 5</td>
</tr>
<tr class="even">
<td>Log monthly income</td>
<td><p>0.0677</p>
<p>(0.2660)</p></td>
<td><p>0.0688</p>
<p>(0.2710)</p></td>
<td><p>0.0828</p>
<p>(0.2750)</p></td>
<td><p>0.3680</p>
<p>(0.6900)</p></td>
<td><p>-1.3840*</p>
<p>(0.8080)</p></td>
</tr>
<tr class="odd">
<td>Hours worked per week</td>
<td><p>0.0237***</p>
<p>(0.0087)</p></td>
<td><p>0.0237***</p>
<p>(0.0087)</p></td>
<td><p>0.0248***</p>
<p>(0.0093)</p></td>
<td><p>0.0247***</p>
<p>(0.0093)</p></td>
<td><p>-0.0551**</p>
<p>(0.0231)</p></td>
</tr>
<tr class="even">
<td>Childhood household size</td>
<td><p>0.1330**</p>
<p>(0.0512)</p></td>
<td><p>0.1330**</p>
<p>(0.0514)</p></td>
<td><p>0.1310**</p>
<p>(0.0519)</p></td>
<td><p>0.5490</p>
<p>(0.9310)</p></td>
<td><p>-2.7360**</p>
<p>(1.2490)</p></td>
</tr>
<tr class="odd">
<td>Number of dependent children</td>
<td><p>-0.3210</p>
<p>(0.2160)</p></td>
<td><p>-0.2020</p>
<p>(5.0530)</p></td>
<td><p>1.0510</p>
<p>(6.1440)</p></td>
<td><p>0.8480</p>
<p>(6.1780)</p></td>
<td><p>-0.0520</p>
<p>(5.9040)</p></td>
</tr>
<tr class="even">
<td>Income × Dependent</td>
<td></td>
<td><p>-0.0114</p>
<p>(0.4840)</p></td>
<td><p>-0.0991</p>
<p>(0.5430)</p></td>
<td><p>-0.0786</p>
<p>(0.5460)</p></td>
<td><p>0.0410</p>
<p>(0.5230)</p></td>
</tr>
<tr class="odd">
<td>Hours worked × Dependent</td>
<td></td>
<td></td>
<td><p>-0.0056</p>
<p>(0.0155)</p></td>
<td><p>-0.0059</p>
<p>(0.0155)</p></td>
<td><p>-0.0103</p>
<p>(0.0149)</p></td>
</tr>
<tr class="even">
<td>Income × Childhood</td>
<td></td>
<td></td>
<td></td>
<td><p>-0.0387</p>
<p>(0.0859)</p></td>
<td><p>0.2120**</p>
<p>(0.1060)</p></td>
</tr>
<tr class="odd">
<td>Hours worked × Childhood</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td><p>0.0111***</p>
<p>(0.0030)</p></td>
</tr>
<tr class="even">
<td>Constant</td>
<td><p>1.6800</p>
<p>(3.2070)</p></td>
<td><p>1.6660</p>
<p>(3.2750)</p></td>
<td><p>1.4150</p>
<p>(3.3590)</p></td>
<td><p>-1.5890</p>
<p>(7.4700)</p></td>
<td><p>21.6400**</p>
<p>(9.4550)</p></td>
</tr>
<tr class="odd">
<td>Observations</td>
<td>149</td>
<td>149</td>
<td>149</td>
<td>149</td>
<td>149</td>
</tr>
<tr class="even">
<td>R-squared</td>
<td>0.1800</td>
<td>0.1800</td>
<td>0.1810</td>
<td>0.1820</td>
<td>0.2600</td>
</tr>
</tbody>
</table>
<p><em>Standard errors in parentheses - [*** p&lt;0.01, ** p&lt;0.05, * p&lt;0.1]</em></p>
<p><em>Other controls are age, educational level, religion and work location</em></p>
<p>Table 7 explores the factors influencing intended fertility among single women. The coefficients for hours worked per week and childhood household size are consistently positive and statistically significant across all models, indicating that an increase in the number of hours worked per week is associated with a higher intention to have children among single women.</p>
<p>This positive relationship suggests that, for single women, working longer hours who grew up in larger families may express a preference for a larger family size in their adulthood. The coefficients for dependent children vary across columns, with a negative coefficient in Model 5 and positive coefficients in other models. However, none of these coefficients are statistically significant at conventional levels, suggesting that the presence of dependent children does not have a clear and consistent impact on the intended fertility of single women in this analysis.</p>
<p>The interaction terms, particularly income/childhood household and hours worked/childhood household, provide additional insights. The joint influence of income and childhood household size has a suppressive effect on intended fertility in one specification, while the joint influence of working longer hours and childhood household size has a consistently positive impact on intended fertility among single women. The positive impact of working longer hours and childhood household size on intended fertility suggests that both career-related considerations and early-life family experiences play a role in shaping fertility intentions among single women.</p>
<p>The lack of consistent significance for income-related variables and the presence of dependent children may indicate that, for single women, other factors not considered in the analysis may be more influential in shaping fertility intentions. However, the lack of consistent significance for income and dependent children highlights the need for further exploration of additional factors that may contribute to the fertility decision-making process among single women.</p>
<p><strong>Table 8: Factors influencing intended fertility among married people</strong></p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<tbody>
<tr class="odd">
<td>VARIABLES</td>
<td>Model 1</td>
<td>Model 2</td>
<td>Model 3</td>
<td>Model 4</td>
<td>Model 5</td>
</tr>
<tr class="even">
<td>Log monthly income</td>
<td><p>-0.1250</p>
<p>(0.1490)</p></td>
<td><p>0.0084</p>
<p>(0.1790)</p></td>
<td><p>0.0605</p>
<p>(0.1790)</p></td>
<td><p>-0.2980</p>
<p>(0.3180)</p></td>
<td><p>-0.3550</p>
<p>(0.3350)</p></td>
</tr>
<tr class="odd">
<td>Hours worked per week</td>
<td><p>-0.0029</p>
<p>(0.0074)</p></td>
<td><p>-0.0035</p>
<p>(0.0074)</p></td>
<td><p>0.0042</p>
<p>(0.0080)</p></td>
<td><p>0.0044</p>
<p>(0.0080)</p></td>
<td><p>-0.0045</p>
<p>(0.0179)</p></td>
</tr>
<tr class="even">
<td>Childhood household size</td>
<td><p>0.1230***</p>
<p>(0.0277)</p></td>
<td><p>0.1250***</p>
<p>(0.0277)</p></td>
<td><p>0.1290***</p>
<p>(0.0275)</p></td>
<td><p>-0.2900</p>
<p>(0.3090)</p></td>
<td><p>-0.4220</p>
<p>(0.3900)</p></td>
</tr>
<tr class="odd">
<td>Number of dependent children</td>
<td><p>-0.0255</p>
<p>(0.1310)</p></td>
<td><p>2.2690</p>
<p>(1.6940)</p></td>
<td><p>4.7480**</p>
<p>(2.0020)</p></td>
<td><p>5.4360***</p>
<p>(2.0610)</p></td>
<td><p>5.6340***</p>
<p>(2.0940)</p></td>
</tr>
<tr class="even">
<td>Income × Dependent</td>
<td></td>
<td><p>-0.2040</p>
<p>(0.1500)</p></td>
<td><p>-0.3360**</p>
<p>(0.1600)</p></td>
<td><p>-0.3970**</p>
<p>(0.1660)</p></td>
<td><p>-0.4100**</p>
<p>(0.1670)</p></td>
</tr>
<tr class="odd">
<td>Hours worked × Dependent</td>
<td></td>
<td></td>
<td><p>-0.0181**</p>
<p>(0.0080)</p></td>
<td><p>-0.0184**</p>
<p>(0.0080)</p></td>
<td><p>-0.0194**</p>
<p>(0.0082)</p></td>
</tr>
<tr class="even">
<td>Income × Childhood</td>
<td></td>
<td></td>
<td></td>
<td><p>0.0361</p>
<p>(0.0265)</p></td>
<td><p>0.0432</p>
<p>(0.0295)</p></td>
</tr>
<tr class="odd">
<td>Hours worked × Childhood</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td><p>0.0010</p>
<p>(0.0018)</p></td>
</tr>
<tr class="even">
<td>Kids number currently</td>
<td><p>0.4080***</p>
<p>(0.0974)</p></td>
<td><p>0.4380***</p>
<p>(0.0996)</p></td>
<td><p>0.3850***</p>
<p>(0.1010)</p></td>
<td><p>0.3930***</p>
<p>(0.1010)</p></td>
<td><p>0.3940***</p>
<p>(0.1020)</p></td>
</tr>
<tr class="odd">
<td>Constant</td>
<td><p>5.2100</p>
<p>(3.2250)</p></td>
<td><p>4.1340</p>
<p>(3.3150)</p></td>
<td><p>1.6810</p>
<p>(3.4580)</p></td>
<td><p>5.6120</p>
<p>(4.5030)</p></td>
<td><p>7.0270</p>
<p>(5.1730)</p></td>
</tr>
<tr class="even">
<td>Observations</td>
<td>250</td>
<td>250</td>
<td>250</td>
<td>250</td>
<td>250</td>
</tr>
<tr class="odd">
<td>R-squared</td>
<td>0.3720</td>
<td>0.3770</td>
<td>0.3900</td>
<td>0.3950</td>
<td>0.3960</td>
</tr>
</tbody>
</table>
<p><em>Standard errors in parentheses - [*** p&lt;0.01, ** p&lt;0.05, * p&lt;0.1]</em></p>
<p><em>Other controls are age, educational level, religion and work location</em></p>
<p>Table 8 explores the factors influencing intended fertility among married people. The coefficients for childhood household size and dependent children are consistently positive and statistically significant across all models. This indicates that individuals who grew up in larger families tend to express a higher intention to have more children in their own marriages. Childhood household size is a significant and positive predictor of intended fertility among married individuals.</p>
<p>The coefficients for the income and dependent children interaction term are consistently negative and statistically significant across all models, suggesting that income has a dampening effect on the positive impact of having dependent children on intended fertility. In other words, higher income reduces the desire for additional children among those who already have dependent children.</p>
<p>The coefficients for the hours worked and dependent children interaction term are consistently negative and statistically significant across all models, indicating the positive impact of working longer hours on intended fertility is reduced when individuals have dependent children. The interaction implies that the combination of long working hours and dependent children moderates the desire for more children. The coefficients for the number of children currently in the household are consistently positive and highly statistically significant across all models and this emphasizes the significance of considering the existing number of children when understanding intended fertility among married individuals. The R-squared values are relatively high, ranging from 0.372 to 0.396, suggesting that the model effectively captures a substantial portion of the variability in intended fertility among married individuals.</p>
<p><strong>Table 9: Factors influencing intended fertility among married men</strong></p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<tbody>
<tr class="odd">
<td>Variables</td>
<td>Model 1</td>
<td>Model 2</td>
<td>Model 3</td>
<td>Model 4</td>
<td>Model 5</td>
</tr>
<tr class="even">
<td>Log monthly income</td>
<td><p>-0.1360</p>
<p>(0.1820)</p></td>
<td><p>0.0174</p>
<p>(0.2220)</p></td>
<td><p>0.0745</p>
<p>(0.2230)</p></td>
<td><p>-0.1480</p>
<p>(0.3870)</p></td>
<td><p>-0.2310</p>
<p>(0.4030)</p></td>
</tr>
<tr class="odd">
<td>Hours worked per week</td>
<td><p>-0.0031</p>
<p>(0.0090)</p></td>
<td><p>-0.0037</p>
<p>(0.0090)</p></td>
<td><p>0.0038</p>
<p>(0.0100)</p></td>
<td><p>0.0038</p>
<p>(0.0100)</p></td>
<td><p>-0.0109</p>
<p>(0.0220)</p></td>
</tr>
<tr class="even">
<td>Childhood household size</td>
<td><p>0.1460***</p>
<p>(0.0335)</p></td>
<td><p>0.1480***</p>
<p>(0.0335)</p></td>
<td><p>0.1530***</p>
<p>(0.0335)</p></td>
<td><p>-0.1090</p>
<p>(0.3740)</p></td>
<td><p>-0.3120</p>
<p>(0.4610)</p></td>
</tr>
<tr class="odd">
<td>Number of dependent children</td>
<td><p>-0.0941</p>
<p>(0.1550)</p></td>
<td><p>2.3090</p>
<p>(1.9890)</p></td>
<td><p>4.5270*</p>
<p>(2.3740)</p></td>
<td><p>4.9720**</p>
<p>(2.4600)</p></td>
<td><p>5.2700**</p>
<p>(2.4950)</p></td>
</tr>
<tr class="even">
<td>Income × Dependent</td>
<td></td>
<td><p>-0.2140</p>
<p>(0.1760)</p></td>
<td><p>-0.3320*</p>
<p>(0.1890)</p></td>
<td><p>-0.3700*</p>
<p>(0.1970)</p></td>
<td><p>-0.3890*</p>
<p>(0.1990)</p></td>
</tr>
<tr class="odd">
<td>Hours worked × Dependent</td>
<td></td>
<td></td>
<td><p>-0.0159*</p>
<p>(0.0094)</p></td>
<td><p>-0.0163*</p>
<p>(0.0095)</p></td>
<td><p>-0.0179*</p>
<p>(0.0097)</p></td>
</tr>
<tr class="even">
<td>Income × Childhood</td>
<td></td>
<td></td>
<td></td>
<td><p>0.0226</p>
<p>(0.0320)</p></td>
<td><p>0.0329</p>
<p>(0.0348)</p></td>
</tr>
<tr class="odd">
<td>Hours worked × Childhood</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td><p>0.0017</p>
<p>(0.0022)</p></td>
</tr>
<tr class="even">
<td>Kids number currently</td>
<td><p>0.4160***</p>
<p>(0.1280)</p></td>
<td><p>0.4570***</p>
<p>(0.1330)</p></td>
<td><p>0.3910***</p>
<p>(0.1380)</p></td>
<td><p>0.3960***</p>
<p>(0.1380)</p></td>
<td><p>0.3940***</p>
<p>(0.1380)</p></td>
</tr>
<tr class="odd">
<td>Constant</td>
<td><p>6.3000*</p>
<p>(3.4090)</p></td>
<td><p>4.4380</p>
<p>(3.7340)</p></td>
<td><p>3.1220</p>
<p>(3.7940)</p></td>
<td><p>5.2220</p>
<p>(4.8270)</p></td>
<td><p>7.2310</p>
<p>(5.5230)</p></td>
</tr>
<tr class="even">
<td>Observations</td>
<td>178</td>
<td>178</td>
<td>178</td>
<td>178</td>
<td>178</td>
</tr>
<tr class="odd">
<td>R-squared</td>
<td>0.3640</td>
<td>0.3700</td>
<td>0.3810</td>
<td>0.3830</td>
<td>0.3850</td>
</tr>
</tbody>
</table>
<p><em>Standard errors in parentheses - [*** p&lt;0.01, ** p&lt;0.05, * p&lt;0.1]</em></p>
<p><em>Other controls are age, educational level, religion and work location</em></p>
<p>Table 9 explores the factors influencing intended fertility among married men. The coefficients for childhood household size and dependent children are consistently positive and statistically significant across all columns. This suggests that men who grew up in larger families with dependent children tend to express a higher intention to have more children in their own marriages. Childhood household size is a significant and positive predictor of intended fertility among married men.</p>
<p>The coefficients for the income/dependent children and hour worked/dependent children interaction terms are consistently negative and statistically significant across all columns. This suggests that income has a dampening effect on the positive impact of having dependent children on intended fertility among married men. Also, the positive impact of working longer hours on intended fertility is reduced when men have dependent children. The coefficients for the number of children currently in the household are also consistently positive and highly statistically significant across all models in Table 9.</p>
<p><strong>Table 10: Factors influencing intended fertility among married women</strong></p>
<table class="table">
<colgroup>
<col style="width: 27%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 14%">
</colgroup>
<tbody>
<tr class="odd">
<td>Variables</td>
<td>Model 1</td>
<td>Model 2</td>
<td>Model 3</td>
<td>Model 4</td>
<td>Model 5</td>
</tr>
<tr class="even">
<td>Log monthly income</td>
<td><p>-0.0498</p>
<p>(0.1880)</p></td>
<td><p>-0.2660</p>
<p>(0.2070)</p></td>
<td><p>-0.2550</p>
<p>(0.1980)</p></td>
<td><p>-0.5310</p>
<p>(0.4770)</p></td>
<td><p>0.4530</p>
<p>(0.5490)</p></td>
</tr>
<tr class="odd">
<td>Hours worked per week</td>
<td><p>-0.0006</p>
<p>(0.0098)</p></td>
<td><p>0.0044</p>
<p>(0.0098)</p></td>
<td><p>0.0164</p>
<p>(0.0107)</p></td>
<td><p>0.0168</p>
<p>(0.0107)</p></td>
<td><p>0.0867***</p>
<p>(0.0250)</p></td>
</tr>
<tr class="even">
<td>Childhood household size</td>
<td><p>-0.0243</p>
<p>(0.0375)</p></td>
<td><p>-0.0328</p>
<p>(0.0365)</p></td>
<td><p>-0.0307</p>
<p>(0.0351)</p></td>
<td><p>-0.3630</p>
<p>(0.5220)</p></td>
<td><p>1.2300*</p>
<p>(0.7130)</p></td>
</tr>
<tr class="odd">
<td>Number of dependent children</td>
<td><p>0.3410</p>
<p>(0.2610)</p></td>
<td><p>-7.7000**</p>
<p>(3.6750)</p></td>
<td><p>-1.2040</p>
<p>(4.4470)</p></td>
<td><p>-0.3690</p>
<p>(4.6590)</p></td>
<td><p>-1.5220</p>
<p>(4.3530)</p></td>
</tr>
<tr class="even">
<td>Income × Dependent</td>
<td></td>
<td><p>0.7260**</p>
<p>(0.3310)</p></td>
<td><p>0.3440</p>
<p>(0.3550)</p></td>
<td><p>0.2510</p>
<p>(0.3860)</p></td>
<td><p>0.3070</p>
<p>(0.3600)</p></td>
</tr>
<tr class="odd">
<td>Hours worked × Dependent</td>
<td></td>
<td></td>
<td><p>-0.0466**</p>
<p>(0.0194)</p></td>
<td><p>-0.0433**</p>
<p>(0.0202)</p></td>
<td><p>-0.0336*</p>
<p>(0.0191)</p></td>
</tr>
<tr class="even">
<td>Income × Childhood</td>
<td></td>
<td></td>
<td></td>
<td><p>0.0291</p>
<p>(0.0456)</p></td>
<td><p>-0.0799</p>
<p>(0.0555)</p></td>
</tr>
<tr class="odd">
<td>Hours worked × Childhood</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td><p>-0.0072***</p>
<p>(0.0024)</p></td>
</tr>
<tr class="even">
<td>Kids number currently</td>
<td><p>0.3880***</p>
<p>(0.0957)</p></td>
<td><p>0.3920***</p>
<p>(0.0927)</p></td>
<td><p>0.3450***</p>
<p>(0.0911)</p></td>
<td><p>0.3520***</p>
<p>(0.0923)</p></td>
<td><p>0.2830***</p>
<p>(0.0889)</p></td>
</tr>
<tr class="odd">
<td>Constant</td>
<td><p>2.6780</p>
<p>(3.0150)</p></td>
<td><p>2.5780</p>
<p>(2.9190)</p></td>
<td><p>0.0236</p>
<p>(2.9980)</p></td>
<td><p>3.4700</p>
<p>(6.1810)</p></td>
<td><p>-11.5200</p>
<p>(7.5620)</p></td>
</tr>
<tr class="even">
<td>Observations</td>
<td>72</td>
<td>72</td>
<td>72</td>
<td>72</td>
<td>72</td>
</tr>
<tr class="odd">
<td>R-squared</td>
<td>0.5090</td>
<td>0.5480</td>
<td>0.5900</td>
<td>0.5930</td>
<td>0.6540</td>
</tr>
</tbody>
</table>
<p><em>Standard errors in parentheses - [*** p&lt;0.01, ** p&lt;0.05, * p&lt;0.1]</em></p>
<p><em>Other controls are age, educational level, religion and work location</em></p>
<p>Table 10 explores the factors influencing intended fertility among married women. The coefficients for the hours worked and childhood household interaction term are consistently negative and statistically significant, implying that the positive impact of working longer hours on intended fertility is reduced for women who grew up in larger families. The interaction effect suggests that the joint influence of work hours and childhood household size negatively affects the desire for more children among married women in the sample. The interaction effects involving income and working hours with dependent children and childhood household size are not robust in this sample, with only the hours worked and childhood household interaction being statistically significant.</p>
<p>The regression analysis provides valuable insights into the factors influencing intended fertility among married women. While some variables such as the presence of dependent children and the number of children currently in the household have a clear impact, the relationships with income, working hours, and childhood household size are less robust in this specific sample. The findings emphasize the multifaceted nature of family planning decisions, influenced by a combination of economic, personal, and familial factors.</p>
</section>
<section id="discussion" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Discussion</h1>
<p>The intersection of education, labor, and fertility has profound implications for demographic transitions. Understanding the interplay between these factors sheds light on evolving societal structures and influences policy decisions. The identified findings from this paper offer valuable insights into the complex dynamics shaping family planning decisions. The observation that more dependent children exert a negative effect on intended fertility aligns with demographic transition theories. As societies progress, there is often a shift towards smaller family sizes. Economic considerations, educational opportunities, and changing societal norms contribute to a desire for fewer children. This finding underscores the role of family planning in response to economic constraints and the desire for improved living standards.</p>
<p>The mitigating effect of income on the negative impact of dependent children suggests the significance of economic empowerment in influencing family planning decisions. Higher income levels provide families with the means to address the challenges associated with raising additional children, such as education and healthcare expenses. It supports the notion that economic development can positively influence fertility patterns, contributing to the demographic transition from high to low fertility rates. The positive effect of longer work hours on intended fertility is an intriguing finding, challenging traditional assumptions about the negative correlation between work commitments and family size. This may indicate evolving attitudes towards work-family balance or a shift in perceptions regarding the compatibility of career aspirations and family life. People with lower wages often find themselves in precarious economic situations, leading to longer working hours as they strive to make ends meet.</p>
<p>The concept of the value of time becomes crucial in understanding how individuals, particularly those with lower incomes, perceive the prospect of having children. For these individuals, time is not merely a measure on the clock; it is a valuable resource directly tied to their financial well-being. With longer working hours, individuals with lower wages may perceive time as a finite resource that could be better allocated to income-generating activities. In the context of fertility intentions, this perception may lead to viewing dependent children as a burden. The rationale behind this perspective is rooted in the economic trade-off between time spent on work and the potential costs associated with raising and caring for children. Furthermore, the lower value placed on time might result in a delay in childbearing, as individuals prioritize economic stability over starting a family. This delay can have cascading effects on fertility rates and population dynamics, contributing to demographic shifts in societies with a prevalence of low-wage workers. However, the diminishing effect as dependent children increase suggests a substitution effect, highlighting the trade-off between time spent at work and family responsibilities.</p>
<p>The conditional nature of the substitution effect on fertility, based on income, underscores the importance of considering economic factors in the relationship between work hours and family planning decisions. This suggests that the ability to outsource childcare or afford support services may influence how individuals perceive the impact of longer work hours on their family life. In economically developed societies, where support services are more accessible, the substitution effect may be more pronounced. The gender disparities observed in the influence of childhood household size on fertility intentions among single individuals highlight the intricate interplay between early-life experiences and later-life decisions. Single women from large childhood households expressing a desire for more children may reflect a deep-seated cultural or familial influence. This indicates the enduring impact of childhood experiences on reproductive attitudes. However, the absence of a similar effect among single men suggests that other factors, such as education or career aspirations, may play a more prominent role in their fertility intentions. Married women, when contemplating fertility intentions, may perceive dependent children as an additional economic burden. This perspective is shaped by the societal expectations placed on women as primary caregivers. The consideration of “many mouths to feed” reflects the economic responsibilities associated with child-rearing, including education, healthcare, and other essentials. The financial strain of providing for a growing family can influence women’s decisions regarding the timing and number of children they desire.</p>
<p>In contrast, married men may view dependent children as economic assets rather than burdens. This perspective stems from traditional gender roles where men are often seen as primary breadwinners. For married men, having children can be perceived as an investment in the family’s economic future. The presence of dependent children may be seen as a source of support, with the expectation that as children grow older, they can contribute to family income and share responsibilities. The differing perspectives between married men and women highlight the intricate interplay of gender roles and societal expectations. While women may perceive the economic challenges associated with raising children, men may see children as potential contributors to the family’s economic well-being.</p>
<p>The divergence in the effect of childhood household size on fertility intentions between married men and women adds complexity to our understanding of family planning within marital relationships. The desire for more children among married men from large childhood households, contrasted with the lack of a similar effect among married women, may be indicative of evolving gender roles within marriages (<span class="citation" data-cites="doepke2016">Doepke and Kindermann (<a href="#ref-doepke2016" role="doc-biblioref">2016</a>)</span>). This dynamic could reflect traditional expectations placed on men as providers or an increased desire for larger families among men. The positive effect of more dependent children on intended fertility for married individuals aligns with historical patterns observed in pre-transitional societies. Larger families were often associated with economic advantages and support systems. However, the diminishing effect as work hours and living costs increase signals a departure from historical norms. Economic considerations and changing societal expectations may be prompting couples to reconsider family size in the face of increased financial and time-related constraints.</p>
<p>The findings from this research work collectively contribute to our understanding of demographic transition by highlighting the intricate interplay between economic factors, work dynamics, and childhood experiences in shaping fertility intentions. Also, the observed gender disparities underscore the importance of acknowledging evolving gender roles and expectations within the family structure. Another contribution of this paper to demographic transition is in the understanding of the diminishing effects of work hours and living costs on fertility intentions, signaling a shift towards smaller family sizes, indicative of a transition towards demographic patterns observed in more developed societies. The implications of these findings on education, labor, and fertility for demographic transition are multifaceted. They emphasize the nuanced factors influencing family planning decisions and offer valuable insights into the evolving landscape of reproductive attitudes. These findings contribute to the ongoing discourse on demographic transitions, providing a deeper understanding of the complex interplay between individual choices, economic considerations, and societal expectations. Acknowledging these dynamics is crucial for policymakers and researchers seeking to navigate the complexities of demographic change and develop interventions that align with evolving societal norms and aspirations.</p>
<div style="page-break-after: always;"></div>
<p><strong>Reference</strong></p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-akresh2009" class="csl-entry" role="listitem">
Akresh, Richard. 2009. <span>“Flexibility of Household Structure: Child Fostering Decisions in Burkina Faso.”</span> <em>Journal of Human Resources</em> 44 (4): 976–97.
</div>
<div id="ref-aladeniyidemographic" class="csl-entry" role="listitem">
Aladeniyi, Paul Olopha Olabimpe. n.d. <span>“Demographic Analysis of the Effect of Some Determinants of Fertility on Fertility Intentions–the Rural and Urban Factor.”</span>
</div>
<div id="ref-balbo2011" class="csl-entry" role="listitem">
Balbo, Nicoletta, and Melinda Mills. 2011. <span>“The Influence of the Family Network on the Realisation of Fertility Intentions.”</span> <em>Vienna Yearbook of Population Research</em>, 179–205.
</div>
<div id="ref-beaujouan2019" class="csl-entry" role="listitem">
Beaujouan, Eva, and Anne Solaz. 2019. <span>“Is the Family Size of Parents and Children Still Related? Revisiting the Cross-Generational Relationship over the Last Century.”</span> <em>Demography</em> 56 (2): 595–619.
</div>
<div id="ref-bonitsis1987" class="csl-entry" role="listitem">
Bonitsis, Theologos Homer, and David T Geithman. 1987. <span>“Does Income Affect Fertility or Does Fertility Affect Income?”</span> <em>Eastern Economic Journal</em> 13 (4): 447–51.
</div>
<div id="ref-doepke2016" class="csl-entry" role="listitem">
Doepke, Matthias, and Fabian Kindermann. 2016. <span>“Bargaining over Babies: Theory, Evidence, and Policy Implications.”</span> National Bureau of Economic Research.
</div>
<div id="ref-dotti2016" class="csl-entry" role="listitem">
Dotti Sani, Giulia M, and Judith Treas. 2016. <span>“Educational Gradients in Parents’ Child-Care Time Across Countries, 1965–2012.”</span> <em>Journal of Marriage and Family</em> 78 (4): 1083–96.
</div>
<div id="ref-duvander2020" class="csl-entry" role="listitem">
Duvander, Ann-Zofie, Susanne Fahlén, Maria Brandén, and Sofi Ohlsson-Wijk. 2020. <span>“Who Makes the Decision to Have Children? Couples’ Childbearing Intentions and Actual Childbearing.”</span> <em>Advances in Life Course Research</em> 43: 100286.
</div>
<div id="ref-gomez2021" class="csl-entry" role="listitem">
Gomez, Daniela. 2021. <em>Stepfather Investment and Reproductive Outcomes Among US Couples</em>. Boise State University.
</div>
<div id="ref-safdari2023" class="csl-entry" role="listitem">
Safdari-Dehcheshmeh, Faranak, Mahnaz Noroozi, Fariba Taleghani, and Soraya Memar. 2023. <span>“Factors Influencing the Delay in Childbearing: A Narrative Review.”</span> <em>Iranian Journal of Nursing and Midwifery Research</em> 28 (1): 10.
</div>
<div id="ref-stewart2002" class="csl-entry" role="listitem">
Stewart, Susan D. 2002. <span>“The Effect of Stepchildren on Childbearing Intentions and Births.”</span> <em>Demography</em> 39: 181–97.
</div>
<div id="ref-tanskanen2014" class="csl-entry" role="listitem">
Tanskanen, Antti O, and Anna Rotkirch. 2014. <span>“The Impact of Grandparental Investment on Mothers’ Fertility Intentions in Four European Countries.”</span> <em>Demographic Research</em> 31: 1–26.
</div>
<div id="ref-vignoli2020" class="csl-entry" role="listitem">
Vignoli, Daniele, Letizia Mencarini, and Giammarco Alderotti. 2020. <span>“Is the Effect of Job Uncertainty on Fertility Intentions Channeled by Subjective Well-Being?”</span> <em>Advances in Life Course Research</em> 46: 100343.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>