---
title: "Use of Long-Acting Reversible Contraceptives in Nigeria: A Scoping Review"
subtitle: Working Paper
description: ""
categories:
  - health
  - working papers
  - citations

date: 2023-05-04
date-modified: today
date-format: "MMM YYYY"

author:
  - name: Chidinma Oli
    affiliations:
      - ref: hdi
    attributes:
      corresponding: true
    email: coli@helpmaninstitute.org
  - name: Benedict Nwogu
    affiliations:
      - ref: uw
    attributes:
      corresponding: false
    email: inwogu@uw.edu
  - name: Edifofon Akpan
    affiliations:
      - ref: hdi
      - ref: unimelb
    attributes:
      corresponding: false
    email: eakpan@helpmaninstitute.org

affiliations:
  - id: hdi
    name: Population Health Sciences, Helpman Development Institute, FCT Abuja, Nigeria.
  - id: uw
    name: School of Pharmacy, University of Washington, Seattle, United States.
  - id: unimelb
    name: School of Population and Global Health, The University of Melbourne, Victoria, Australia.

format: 
  html:
    default-image-extension: svg
    anchor-sections: true
    toc-location: left
    fig-cap-location: margin
    output-file: larcs-scoping-review.html
  pdf:
    default-image-extension: pdf
    link-citations: true
    linestretch: 1.25
    geometry:
    - top=25.4mm
    - left=25.4mm
    - right=25.4mm
    - bottom=25.4mm
    extra_dependencies: ["flafter"]
    output-file: larcs-scoping-review.pdf
    header-includes: |
      \usepackage[labelsep=period]{caption}

editor: visual
crossref:
  title-delim: "."
number-sections: true

toccolor: blue
toc: true
toc-depth: 2
toc-title: "Table of Contents"
execute:
  echo: false
bibliography: references.bib
pdf-engine: lualatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width = 12, fig.height = 10, fig.align = "center",
                      out.width = "100%", collapse = TRUE, fig.pos = "H", out.extra = "")
```

{{< pagebreak >}}

Universal provision of iron supplements or iron-containing multiple micronutrients powders (MNPs) are widely used to prevent anemia in young children in low- and middle-income countries. The Benefits and Risks of Iron Interventions in Children (BRISC) trial compared iron supplements and MNPs with placebo in children under 2 years in rural Bangladesh.

Universal provision of iron supplements or iron-containing multiple micronutrients powders (MNPs) are widely used to prevent anemia in young children in low- and middle-income countries. The Benefits and Risks of Iron Interventions in Children (BRISC) trial compared iron supplements and MNPs with placebo in children under 2 years in rural Bangladesh.

Universal provision of iron supplements or iron-containing multiple micronutrients powders (MNPs) are widely used to prevent anemia in young children in low- and middle-income countries. The Benefits and Risks of Iron Interventions in Children (BRISC) trial compared iron supplements and MNPs with placebo in children under 2 years in rural Bangladesh.

Universal provision of iron supplements or iron-containing multiple micronutrients powders (MNPs) are widely used to prevent anemia in young children in low- and middle-income countries. The Benefits and Risks of Iron Interventions in Children (BRISC) trial compared iron supplements and MNPs with placebo in children under 2 years in rural Bangladesh.
