---
title: "Policy-Relevant Economic Research in Africa"

categories:
  - Blog & commentary

date: 2023-01-04
#date-modified: today
date-format: "MMM YYYY"

author:
  - name: Olumide Taiwo
    affiliations:
      - ref: hdi
    attributes:
      corresponding: true
    email: otaiwo@helpmaninstitute.org
affiliations:
  - id: hdi
    name: Helpman Development Institute, FCT Abuja, Nigeria.

format: 
  html: 
    fig-cap-location: margin
execute:
  echo: false
---

# **Why Research?**

The essence of research is knowledge production, or betterstill, discovery of the world around us. There are two reasons why anyone would want to do or fund research. One, we want to understand how our societies work. Studies spurred by this motive are basic in nature and are more often than not theoretical. Second, we want answers to specific questions. Such research is termed applied research. These questions are typically causal in nature and are of two types: those seeking to establish the direction of causation, asking whether increase in a variable causes increase in another, and those seeking to estimate the exact causal effect of one variable on the other. However, in general, applied research tends to take the form of the latter; the sponsors of a research are likely to be interested not merely in how a variable affects another but by how much? This latter question is usually harder to answer than the former.

In observing the world around us through data, the researcher seeks to discover the data generating process (DGP) of a particular outcome -- what are the important determinants, what are their independent effects, how do they interact to produce the outcome we observe and what is the best way to describe or model this process? This is the crucial knowledge that feeds policymaking! This is the knowledge we require -- regarding important issues -- if we are going to change the society and our world. Until we can demonstrate that we understand the process correctly and can distinguish it from alternative processes, it is not clear that research can be useful in our contexts. If we do not understand the society, we cannot help it or change it in a meaningful and targeted way. The alternative is to rely on pure luck! The problem is that luck does not run very far. Having grand ideas and desires does not matter; if we cannot discover the DGP, we have not done anything useful.

# **The Place of Data**

It is an obvious fact that no nation can produce sound and rigorous research (and science in general) more than it collects good data. Quality and comprehensive datasets allow people to observe, think, model and remodel, discover the society through produce credible evidence, and solve relevant problems. I don't see how we can do rigorous economic research in the absence of good data! It goes without saying that the first step to accelerate knowledge production is to invest in data collection.

Be that as it may, there is an additional problem with data collection. It is futile from hindsight to collect data in ways that abstract from society. It is rather appalling that development institutions would sponsor data collection and in the questionnaires ignore basic features of society. For example, it is well understood that the basic sphere of resource allocation and public good sharing in African societies is not the household but the extended family. Taking the nuclear household or the set of people residing within the walls of a building as constituting the entire sphere of decision making and resource allocation is simply silly. One would be looking at one of the leaking pots that are contained in a much bigger and well sealed pot. Despite the plethora of anthropological evidence to this effect, the World Bank Living Standard Measurement Surveys were designed in ways that view an African household as organized in ways similar to an American household. My most recent survey of datasets across Africa led me to only one place -- the Agincourt Demographic and Health Surveillance surveys in Northern Province in South Africa -- where interhousehold connections were deemed important. Viewing households in developing societies as independent economic units is just not consistent with what anthropologists have showed us!

# **Social Contexts in Research**

Defining economics as what economists do, economic research aims to generate or refine knowledge about allocation of scarce resources and the efficiency of specified allocations. Of course, economic activities do not take place in vacuum. Resource allocation is importantly characterized by the structure of incentives -- opportunities and constraints reflected in the costs and benefits -- inherent in the institutional setting, and these institutions could vary from one social context to another. There is a tendency, which I think is dangerous, to ignore social contexts in the pursuit of knowledge about issues that we consider as economic in nature. Because the data do not reflect society, such research efforts however grand they are will only produce "knowledge you can't use."

This realization brings with it two important implications. Of course I have assumed that the focus of inquiry is important for welfare improvement. First, the researcher needs to carefully observe society, ask initial questions on the subject of interest, and probe deeply to have a fair idea of the process that the research is aiming to uncover. Second, research does not necessarily have to begin with writing an introduction and literature review of a subject. Most often than not, influential research does not begin with getting buried into the books and papers! Sometimes, the question that a researcher initially thinks is important will end up as unimportant after asking questions about the society. For example, a researcher could be interested in improving the lives of a rural agricultural population where cattle and wood exist but cattle-driven ploughs are non-existent. The researcher could then embark on an inquiry about efficiency of cattle market: the idea that a market for cattle could allow farmers to buy cattle to create ploughs which in turn will help raise productivity and raise welfare. Suppose cattle are only given as bride price at the time of marriage and cattle trade is forbidden according to the norms. If the researcher takes time to ask questions from the people what they do with cattle and wood, and why they use cattle for bride-price and not for other means, he will quickly discover that a cattle market is a non-issue in the village and perhaps must ask a different question. Omitting this important step is akin to "putting the cart before the horse."

# **Ruling Paradigm**

A typical research paper produced in indigenous African university or research institution follows more or less a rigid structure. The paper begins with framing the issue and discussing its relevance to humanity in the introduction, the literature search, the statement of the problem, the objectives of the research which are translated into corresponding hypotheses to be tested, a litany of existing models collected from around the globe and final selection of one of them to be used for the purpose of the paper, the research methodology, the data, empirical results, summary and conclusion. In fact, materials contained in the sections beginning from introduction to methodology constitute the research proposal. Once the data is acquired and analyzed, the only thing left is to append the statistical test results and the inferences to be made from them. The paper is done!

The process outlined also has a history. Until recently when the need to understand societies began to gain traction, most research and training programs were almost exclusively focused on macroeconomic topics such as inflation, interest rate, trade, balance of payments, and unemployment to mention a few. Indeed, the focus on macroeconomics topics were driven by data that were available and well known as well as dependence on knowledge generated from developed countries. Data sets analyzed were typically time series for studies of national phenomenon and multiple countries' time series for studies of regional phenomenon. Since most macroeconomic concepts are typically thought to conform to standard models, there are no reasons why standard macroeconomic models that have been tested somewhere in the developed world should not be the ones applicable in the developing world. Minor distinctions or minor adjustments could be made to models while applying them elsewhere. For example, a model suited to large countries might require some slight adjustment when applied to small countries.

Academic training followed the knowledge dependence hypothesis where knowledge flowed from the developed world to the developing world. Most of early faculties in African institutions were trained in the west; indeed this was quite common before the cold war. Colonial masters typically sent indigene Africans abroad for doctoral training and brought them back home to help train others. It is also the case that most of those trained this way were trained mainly in the methods of macroeconomic thinking.

This style of doing macroeconomic research has been transported into microeconomic research. As a result, students are boxed into a corner in such a way that it is often hard to make new discoveries. I had a chance to supervise master's students at Witwatersrand, and this is what I observed. About eight in ten of students wanted to write their thesis on topics like "the socioeconomic determinants of ...." I got tired of it and jokingly asked one student who told them that is what they should be doing? Are those theses going to inform any kind of serious decision-making? I agree they were good topics in the 1980s and even now, but these days we want to know the causal effect of important factors. We want to know what we don't know yet! We just don't want to rerun a model that has been run in India in Zambia. I think these are serious issues that are worth considering. How do we get out of working on safe topics that the process can allow us to examine? I understand that they are forced into those topics by the dissertation process.

# **What has changed?**

Data collection efforts at microeconomic levels have proliferated greatly since the end of the cold war, and this development has marked a great shift toward empirical microeconomic research. The proliferation of datasets comes with another development. These data shed insights into problems with inferences previously made about several phenomena that were not recognized then. For instance, the issue of selection was not widely recognized until James Heckman published a paper in 1979. Even sociologists now are more prone to mention the word "selection" than economists are. Indeed, as more datasets became available, many empirical problems that were previously unrecognized began to gain recognition and econometrics advanced rapidly. As a result, the task of establishing that you have made a discovery is far more daunting[^1]. In fact, the more important task is not about trying to establish the idea you think you have found, but to fend off and rule out other potential interpretations of the findings. No one will believe that a serious contribution has been made until those alternative interpretations have been shut down. Now, all those alternative interpretations arise from theoretical or econometric reasoning. If a researcher knows that what is most important in the paper is the evidence and that the entire writing will make no meaning unless there is a clear demonstration that credible evidence has been found, it is clear that spending time on literature before looking at the data is not the wise way to spend research time. In fact, if I know that the quality of the paper depends more importantly on the evidence than anything else, then I should establish the evidence before doing anything else.

[^1]: In fact, any current paper written the same way as many papers published in the 1960s and 1970s will not be published. For example, many people used the World Bank sponsored Living Standards Measurement Surveys to write papers that were published in the 1980s. It's going to be hard to publish articles using those datasets in those journals today. Why? Many issues that were not recognized as important then are well recognized today.

More than anything else,availability of new data should lead to breaking new grounds. These new data, if well inspected, could provide insights into breaks with the past in ways that have not been previously understood. It is hard to break new grounds if one must always begin with the past. Indeed, the idea that research must begin with the literature and existing models, after framing the issue has a potential flaw. First, some good research papers and discoveries prop up by unintentionally stumbling on something! It's not even the issue that the researcher has thought about! Second, burying one's head into the literature and existing models may actually keep a person squarely inside the box and unable to get out! In this case, it's counterproductive to begin there! The idea of writing a model before the research is done is the single most important problem from my viewpoint! Unless one is writing a theoretical paper or doing an empirical test of an existing theory or (repeat) testing a theory that was tested in Finland in Ghana, I am not sure that existing theories are the first place to go. Let's think of this. If a model fitted data from the Peruvian society, what is the basis for being the model that should fit the Malawian society? Unless the researcher allows himself to think more intensely about Malawi, and this is possible only by examining data from Malawi, it is more likely that the very important thing that distinguishes Malawi from Peru (except significance or differences in the size of coefficient estimates) will be lost! What the researcher needs to discover in Malawi would have been given away.

One thing that I also think has changed is the purpose of research. Research can be done with the intention of racking up articles and demonstrating one's productivity and mastery of skills, or with the intention of changing the world. The economics profession (as practiced in North America) seems to have decided largely for the former. I think this shift is informed by failure of the policies they have advanced in the past, particularly relating to development, that have fallen flat! I think that failure was admitted in a flawed way. I remember when I went to Yale, the professors made clear that they do not intend to advise governments on what to do. That is, they are just doing their things. If you attend development conferences, you'll realize that these folks are not interested in changing the world; they just want to enjoy what they are doing and become experts in their fields. But we learn some things from their works. That viewpoint has created problems for those with the latter intention. They must demonstrate that they can do the same thing as those professionals before their evidence can be taken seriously. It is either you are there or you are out!

# **Beware of Tyranny**

The most important danger to policymaking is the "tyranny of dead ideas." Before the recent advances in the tools of econometric analysis, the foremost development economists simply observed events, imagined what could be the explanation according to economic theories and laid down new theories that have become the rules of the thumb. In a lot of ways, these rules are just taken as settled. For example, there is a rule that says a country must have high inequalities in order to grow. But of course we have just witnessed unprecedented rate of inequality in an economy that has had enviable long run growth. Despite the experiences, this rule is virtually repeated as true almost in any study of inequality, whether in developed or developing economies. The troubling part of it is that the rule is cited without reference to the social and policy environment that produced those outcomes.

# **The role of mentoring**

If someone comes up to me and describes an empirical research interest, the first thing I ask the student is why it's an important question. After this, the next thing I ask it for the student to write down the idea in terms of an econometric model and define the variables on both sides of the equation (I don't say go and write an introduction and literature review). The next thing is to help think through the implications of potential findings and the alternative interpretations of such findings, and how to deal with the various empirical issues. That discussion and understanding of the various issues the individual has to contend with are the guides for data search. If appropriate data does not exist (sometimes administrative and survey datasets could be combined) for the purpose, then it is important to set on the journey of collecting data.

Of course, the process outlined in the preceding paragraph requires that I stay current with the literature in the area in which I am advising a student! It requires that I know the issues and can easily refer the student to how those issues have been explored. Perhaps, this is where the problem lies. If I don't know where the cutting edge is, I cannot guide the student this way and I have to send him to the old school.

# **The danger of the old school**

On another note, there are different types of research and different types of research outputs. For some outputs, readers want to know the entire work from reading the introduction. They have tons of papers to read! So, if I have to write an introduction before seeing the data, then I must be prepared to write it again after seeing the data because the paper will not be read if they can't understand the entire work from the introduction. If I wrote the model before looking at the data (except the case where I'm just testing an existing model), then I must be prepared to rewrite the model that fits the data once I'm done understanding the data. This writing and rewriting can just lengthen the process of graduating and create redundancies.

# **Recommendation**

Before a student is asked to submit a dissertation proposal, there is a need to allow for a sketchy pre-dissertation proposal, exploratory study that may involve travel and initial interviews on an area of interest. This stage allows the student to gain insight into how the society is organized and what are the important characteristics that may affect the subject of interest. The student thereafter develops a dissertation proposal and search for relevant and suitable data. In the event that the data available are unsuitable, the candidate goes ahead to design a survey based on the findings during the pre-dissertation phase.
