<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Chukwuma Nwofor">
<meta name="author" content="Halimat Abdulrazaq">

<title>Helpman Institute - 
Employment choice and earnings analysis of FCT labour force: an examination of determinants and motivations.</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Helpman Institute</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html" rel="" target="">
 <span class="menu-text">Research</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:info@helpmaninstitute.org" rel="" target=""><i class="bi bi-envelope" role="img" aria-label="email">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/company/helpmaninstitute" rel="" target=""><i class="bi bi-linkedin" role="img" aria-label="linkedin">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of Contents</h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#concept-clarification" id="toc-concept-clarification" class="nav-link" data-scroll-target="#concept-clarification"><span class="header-section-number">2</span> Concept clarification</a></li>
  <li><a href="#literature-review" id="toc-literature-review" class="nav-link" data-scroll-target="#literature-review"><span class="header-section-number">3</span> Literature review</a></li>
  <li><a href="#methodology-and-data" id="toc-methodology-and-data" class="nav-link" data-scroll-target="#methodology-and-data"><span class="header-section-number">4</span> Methodology and data</a></li>
  <li><a href="#data-analysis" id="toc-data-analysis" class="nav-link" data-scroll-target="#data-analysis"><span class="header-section-number">5</span> Data analysis</a>
  <ul class="collapse">
  <li><a href="#workers-characteristics" id="toc-workers-characteristics" class="nav-link" data-scroll-target="#workers-characteristics"><span class="header-section-number">5.1</span> Workers’ characteristics</a></li>
  <li><a href="#wage-employment-workers-characteristics" id="toc-wage-employment-workers-characteristics" class="nav-link" data-scroll-target="#wage-employment-workers-characteristics"><span class="header-section-number">5.2</span> Wage employment workers characteristics</a></li>
  <li><a href="#self-employed-workers-characteristics" id="toc-self-employed-workers-characteristics" class="nav-link" data-scroll-target="#self-employed-workers-characteristics"><span class="header-section-number">5.3</span> Self-employed workers characteristics</a></li>
  <li><a href="#workers-transition-statistics" id="toc-workers-transition-statistics" class="nav-link" data-scroll-target="#workers-transition-statistics"><span class="header-section-number">5.4</span> Workers’ transition statistics</a></li>
  <li><a href="#evaluation-of-workers-parents-employment" id="toc-evaluation-of-workers-parents-employment" class="nav-link" data-scroll-target="#evaluation-of-workers-parents-employment"><span class="header-section-number">5.5</span> Evaluation of workers’ parents’ employment</a></li>
  <li><a href="#regression-results" id="toc-regression-results" class="nav-link" data-scroll-target="#regression-results"><span class="header-section-number">5.6</span> Regression results</a></li>
  </ul></li>
  <li><a href="#conclusion-and-policy-recommendations" id="toc-conclusion-and-policy-recommendations" class="nav-link" data-scroll-target="#conclusion-and-policy-recommendations"><span class="header-section-number">6</span> Conclusion and policy recommendations</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="employment-choice-analysis.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><img src="resources/hdi_logo.png" class="img-fluid" style="width:2in"><br>
Employment choice and earnings analysis of FCT labour force: an examination of determinants and motivations.</h1>
<p class="subtitle lead">Working paper</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Chukwuma Nwofor </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Helpman Development Institute, FCT Abuja, Nigeria.
          </p>
      </div>
      <div class="quarto-title-meta-contents">
    <p class="author">Halimat Abdulrazaq </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Helpman Development Institute, FCT Abuja, Nigeria.
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Jan 2024</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">Feb 2024</p>
    </div>
  </div>
    
  </div>
  

</header>

<div style="page-break-after: always;"></div>
<p><strong>ABSTRACT</strong></p>
<p><em>This study examines the factors affecting income levels, reservation income expectations, and employment sector transition choices in the Nigerian economy. We employed descriptive tables, Mincerian regression models, and multinomial logit regression models to analyze workers’ employment transition motivations and economic constraints. Data from a multipurpose survey carried out by Helpman Development Institute Garki 2, Abuja, which focused on employment sector choices, income levels, reservation wage expectations, fertility decisions, and insurance knowledge is used in this research endeavor. Finding show that majority of FCT workers plan to become employers in five years’ time. We also find that monthly living costs, educational level (specifically possessing a national diploma or higher), gender, an individual’s employment sector, and apprenticeship experience significantly influence income levels of FCT workers. The research findings also suggest that FCT workers with a Bachelor’s degrees or higher had notable reservation wage expectations, while gender did not significantly influence reservation income expectations. Our research findings also indicate that larger childhood household sizes increase the probability of transitioning into the self-employment sector from wage/salary employment and also from self-employment to employer sector. The major policy implication of our results is the need to provide a stable environment for the growth and expansion of businesses as we see that majority of FCT workers intend to become employers or self-employed workers in five years’ time, their major motivation being in search of a better room for growth and expansion.</em></p>
<p><strong>Key words</strong>: multinomial logistic regression, income, Nigerian, transition</p>
<div style="page-break-after: always;"></div>
<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Wage determination, as well as the various reasons for seeking to switch employment sectors has been an area of continued concern in the Nigerian labour market. We believe that by understanding the economic constraints, expectations and motivations behind future employment choices, a better understanding of the Nigerian labour market will be available for effective policy creation.</p>
<p>For the purpose of this paper, the Nigerian labour force is divided into 5 major groups namely; wage/salary employment, self-employment, employer, family-enterprise, and unemployed. Each of these categories has peculiarities, but income and wage inequality are common features. As a result, mobility across different jobs within and beyond the informal sector and is often pronounced, albeit with some constraints. Specific attention is laid on the prospective employment sector choices of workers by examining their motivations and constraints.</p>
<p>We apply descriptive tables, Mincerian regression models, and employment transition regression models in analyzing the motivations of workers’ prospective employment sector choices as well as their current economic constraints and reservation wage expectations. We find that the major factoring influences wage determination in the regression models are monthly living cost, educational level i.e., possessing a national diploma or higher, gender, employment sector, and apprenticeship experience. For the reservation wage model, we see that workers with Bachelor’s or Postgraduate degree had significant expectations while workers with national diplomas did not. As expected, gender did not have a significant effect on reservation wage expectations. The potential employment transition regressions tell us that having larger childhood household sizes increases the likelihood of transitioning from wage employment to self-employment as well as self-employment to employer sector. We also see that having apprenticeship experience strongly increases the likelihood of transitioning from wage employment to employer sector and even more so for self-employment to wage employment sector, this is a unique finding as it could be interpreted to mean that possessing apprenticeship experience makes the transition across employment sectors smoother.</p>
<p>The rest of the paper is made up of 5 sections. Section 2 provides an explanation of labour market groupings and important concepts used for this study. In Section 3 we explore the extant literature on wage determination, labour market dynamics, and labour market transition. Section 4 is dedicated to the description of the methodological approach and source of data used in the study. A descriptive and empirical data analysis is presented in Section 5. Finally, in Section 6 concluding remarks and policy recommendations are provided.</p>
</section>
<section id="concept-clarification" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Concept clarification</h1>
<p><strong>Wage/salary employment:</strong> Individuals under a formal form of employment with a standard employment contract.</p>
<p><strong>Self-employment;</strong> Individuals with their own enterprise/business, or individuals who work with a maximum of two other persons without any of them bearing the identity of a boss or an employer.</p>
<p><strong>Employer:</strong> Individuals who have at least three (3) employees working and getting paid under them.</p>
<p><strong>Family-enterprise:</strong> Individuals who work in an enterprise belonging to a family member without a standard employment contract/wage.</p>
<p><strong>Unemployed:</strong> Individuals who currently don’t have any form of employment, are not under contract of receiving wage/salary and have not done any job for profit/pay in the past seven (7) days at the time of the survey.</p>
<p><strong>Apprenticeship:</strong> This is defined as the participation in the learning of a crude hand-work such as; hair-dressing, tailoring, bricklaying, automobile fixing under the supervision of an experienced individual in the field. Information Communication and Technology (ICT) skills were also considered under this heading.</p>
</section>
<section id="literature-review" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Literature review</h1>
<p><strong>Wage determination</strong></p>
<p>Empirical literature on determinants of earnings is vast, wage determination is a complex process influenced by various factors, both individual and external. Literature has shown that socio-demographic factors such as age, sex, and education influence wage determination ( <span class="citation" data-cites="garofalo2016">Garofalo, Agovino, et al. (<a href="#ref-garofalo2016" role="doc-biblioref">2016</a>)</span>; <span class="citation" data-cites="guven2018">Guven-Lisaniler, Tuna, and Nwaka (<a href="#ref-guven2018" role="doc-biblioref">2018</a>)</span>; <span class="citation" data-cites="jimohsocial">Jimoh (<a href="#ref-jimohsocial" role="doc-biblioref">n.d.</a>)</span>). It is important to note that empirical findings had shown that the returns to education on wages can vary substantially, <span class="citation" data-cites="thurow1975">Thurow (<a href="#ref-thurow1975" role="doc-biblioref">1975</a>)</span> using 1972 data, found that 28 percent of people with university education had negative returns to education while only 24 percent had positive return. In recent studies, results have shown that female workers are even experiencing higher wage returns to education than their male counterparts <span class="citation" data-cites="samahiya2023">Samahiya and Wirba (<a href="#ref-samahiya2023" role="doc-biblioref">2023</a>)</span>, This further speaks to the significant effect educational level has on wage determination in the modern world. Workers are concerned with the immediate quantum of disposable income ( <span class="citation" data-cites="duncan1989">Duncan and Hill (<a href="#ref-duncan1989" role="doc-biblioref">1989</a>)</span>; <span class="citation" data-cites="poole1998">Poole and Jenkins</span>) and as such, wage levels play a pivotal role in deciding to switch employment sectors.</p>
<p><strong>Nigerian labour market dynamics</strong></p>
<p>The Nigerian labour market is characterized by heterogeneity and dualism, which are the general features of most African and developing countries’ labour markets ( <span class="citation" data-cites="aminu2016">Aminu</span>; <span class="citation" data-cites="fields2011">Fields (<a href="#ref-fields2011" role="doc-biblioref">2011</a>)</span>; <span class="citation" data-cites="gupta1984">Gupta (<a href="#ref-gupta1984" role="doc-biblioref">1984</a>)</span>). The formal labour market comprises public sector organizations and large private firms, while the informal segment is made up of micro, small, and medium-scale enterprises, petty trades, and other forms of individual economic activity. Essentially, the formal and informal sectors differ in terms of governance and regulatory framework, employment process, employees’ compensation (wage determination), and productivity. Because of the poor remuneration and working conditions in the informal sector, workers often transit from the informal to the formal sector, while there is little reverse transition usually brought about by retirement or retrenchment from formal jobs <span class="citation" data-cites="ikechukwu2016">Ikechukwu Darlington (<a href="#ref-ikechukwu2016" role="doc-biblioref">2016</a>)</span>. This is issue of employment transitions is explored in detail from a new angle in this research paper and interesting insights are drown from the descriptive and regression analyses.</p>
<p><strong>Labour market transitions</strong></p>
<p>Previous research has also shown that there is a high level of employment transition to and from the informal and formal sector of the Nigerian labour market <span class="citation" data-cites="folawewo2020">Folawewo and Orija (<a href="#ref-folawewo2020" role="doc-biblioref">2020</a>)</span>. Although the transition from informal wage and self-employment sector to the formal sector has been seen to be more likely, formal workers transitioning to informal employment is less likely. Another major factor that has been known to be a major determinant of employment transition is the nature of a worker’s parent employment. Workers who have parents that work or worked in self-employment are more likely to tread the same path ( <span class="citation" data-cites="krumboltz1976">Krumboltz, Mitchell, and Jones (<a href="#ref-krumboltz1976" role="doc-biblioref">1976</a>)</span>; <span class="citation" data-cites="olaposi2014">Olaposi, Adelowo, and Akintelu (<a href="#ref-olaposi2014" role="doc-biblioref">2014</a>)</span>). These links between parents’ employment and worker’s intended employment status are explored in the descriptive data analysis section of this paper. Moving away from the employment status of worker’s parents or guardians, minimum wage has also been known to have a significant effect on employment choice, especially on low wage workers. <span class="citation" data-cites="kawaguchi2007">(<a href="#ref-kawaguchi2007" role="doc-biblioref">Kawaguchi and Yamada 2007</a>)</span>.</p>
</section>
<section id="methodology-and-data" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Methodology and data</h1>
<p>The prospective employment choice of the Federal Capital Territory (FCT) labour force is evaluated using descriptive analysis. This involved measuring the percentage of individuals involved in the various employment types, analyzing the characteristics of such individuals using diverse cross-tabulations. The analysis of determinants of monthly income and reservation income were estimated using Ordinary Least Square (OLS) regression models while the probability of transitioning from wage/salary employment or self-employment to specific employment sectors was estimated used multinominal logistic regression models. The first transition model estimated the transition from wage employment to either self-employment or employer sector with the baseline category being the respondents that chose to remain in wage/salary employment. The second transition model estimated the probability of transitioning from self-employment to either wage-employment or employer sector with the baseline category being the respondents that chose to remain in self-employment.</p>
<p>The study utilized data from a multidisciplinary survey carried out by <strong>Helpman Development Institute (HDI) Garki II, Abuja</strong> from October 9th to October 24th 2023 that sought to gather data on employment sector (labour) choices, current wage/income levels, reservation income expectations, fertility choices, and insurance knowledge. Respondents were randomly selected from 10 major parts of Abuja (FCT). The survey recorded 842 responses. For the benefit of this research paper, data was mostly drawn from the background and labour section of the questionnaire.</p>
</section>
<section id="data-analysis" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Data analysis</h1>
<p>As a means of achieving the objectives of the study, empirical analysis is carried out in three stages. First, a descriptive analysis is carried out to ascertain workers intended employment status and their motivations for picking it and their current monthly income as well as their reservation wage expectations. Second, Mincerian regression models are employed to analyze of the impact of various factors on monthly income and reservation income values. The third phase involves an examination of potential employment transition of workers who are currently wage or self-employed, evaluating their possibility of transitioning to either self-employment, wage employment, or employer status based on selected control variables. A multinomial logistic regression was employed in this third phase.</p>
<section id="workers-characteristics" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="workers-characteristics"><span class="header-section-number">5.1</span> Workers’ characteristics</h2>
<p><strong>Labour force distribution by gender</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure1.png" class="img-fluid figure-img" alt="Source: authors’ computation from survey data" width="550"></p>
<figcaption class="figure-caption">Labour force distribution by gender</figcaption>
</figure>
</div>
<p>The distribution of respondents based on gender and current employment sector is depicted in Figure 1 above. We see that majority of the male and female survey respondents currently work in the wage employment or self-employment sector, while the second largest group from both genders work in self-employment. Notably, there are more female family enterprise workers than male ones. We also see from the table that there are more male employers than female employers in the survey respondents.</p>
<p><strong>Labour force distribution by age</strong></p>
<table class="table">
<caption>Tabulation showing labour force distribution by age-range</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Employment Sector</th>
<th></th>
<th></th>
<th></th>
<th>Age Range</th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td><strong>15-17</strong></td>
<td><strong>18-24</strong></td>
<td><strong>25-34</strong></td>
<td><strong>35-49</strong></td>
<td><strong>50-59</strong></td>
<td><strong>70+</strong></td>
<td><strong>TOTAL</strong></td>
</tr>
<tr class="even">
<td>Employer</td>
<td>1</td>
<td>2</td>
<td>21</td>
<td>19</td>
<td>8</td>
<td>0</td>
<td>53</td>
</tr>
<tr class="odd">
<td>Family Enterprise</td>
<td>4</td>
<td>9</td>
<td>13</td>
<td>10</td>
<td>1</td>
<td>0</td>
<td>38</td>
</tr>
<tr class="even">
<td>Self Employed</td>
<td>2</td>
<td>35</td>
<td>133</td>
<td>44</td>
<td>12</td>
<td>1</td>
<td>230</td>
</tr>
<tr class="odd">
<td>Unemployed</td>
<td>8</td>
<td>22</td>
<td>21</td>
<td>3</td>
<td>3</td>
<td>0</td>
<td>57</td>
</tr>
<tr class="even">
<td>Wage/Salary Employee</td>
<td>8</td>
<td>105</td>
<td>245</td>
<td>97</td>
<td>7</td>
<td>0</td>
<td>464</td>
</tr>
<tr class="odd">
<td><strong>TOTAL</strong></td>
<td>23</td>
<td>173</td>
<td>433</td>
<td>173</td>
<td>31</td>
<td>1</td>
<td><strong>842</strong></td>
</tr>
</tbody>
</table>
<p><em>Source: authors’ computation from survey data</em></p>
<p>From the age distribution table above, we see that majority of the respondents fall into the ages 18-49, with the highest group falling into the 25-34 age bracket. The wage/salary employed and self-employed workers’ which are the focus of this paper are well represented across all age-groups, with the highest numbers in the 25-34 and 35-49 age ranges.</p>
<p><strong>Labour force distribution by educational level</strong></p>
<table class="table">
<caption>Tabulation of worker’s current employment sector and educational level</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 23%">
<col style="width: 22%">
<col style="width: 15%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>Current Employment sector</th>
<th></th>
<th>Education Level</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td><strong>Secondary School &amp; below</strong></td>
<td><strong>National Diploma</strong></td>
<td><strong>BSc &amp; above</strong></td>
<td><strong>TOTAL</strong></td>
</tr>
<tr class="even">
<td>Employer</td>
<td>14</td>
<td>9</td>
<td>30</td>
<td><strong>53</strong></td>
</tr>
<tr class="odd">
<td>Family Enterprise</td>
<td>23</td>
<td>8</td>
<td>7</td>
<td><strong>38</strong></td>
</tr>
<tr class="even">
<td>Self Employed</td>
<td>100</td>
<td>54</td>
<td>76</td>
<td><strong>270</strong></td>
</tr>
<tr class="odd">
<td>Unemployed</td>
<td>34</td>
<td>5</td>
<td>18</td>
<td><strong>57</strong></td>
</tr>
<tr class="even">
<td>Wage/Salary Employee</td>
<td>133</td>
<td>82</td>
<td>249</td>
<td><strong>464</strong></td>
</tr>
<tr class="odd">
<td><strong>TOTAL</strong></td>
<td><strong>304</strong></td>
<td><strong>154</strong></td>
<td><strong>380</strong></td>
<td><strong>842</strong></td>
</tr>
</tbody>
</table>
<p><em>Source: authors’ computation from survey data</em></p>
<p>Table 2 above shows a cross tabulation of the highest educational attainment of the survey respondents against their current employment status. We see that majority of individuals possess a Bachelor’s degree or higher (380) while significant responses were also gathered across the other two groups; Secondary school and below (304), National diploma (158). Majority of individuals across the three educational levels work in wage/salary employment while the second largest group work in self-employment.</p>
</section>
<section id="wage-employment-workers-characteristics" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="wage-employment-workers-characteristics"><span class="header-section-number">5.2</span> Wage employment workers characteristics</h2>
<table class="table">
<caption>Tabulation of currently wage/salary employed worker’s statistics</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 1%">
<col style="width: 17%">
<col style="width: 9%">
<col style="width: 2%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;"></th>
<th style="text-align: center;">WAGE</th>
<th style="text-align: center;">EMPLOYMENT</th>
<th></th>
<th style="text-align: center;"></th>
<th style="text-align: center;">STATISTICS</th>
<th></th>
<th style="text-align: center;"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">WAGE EMPLOYMENT GROUPS</td>
<td style="text-align: center;"><strong>Income (Mean)</strong></td>
<td style="text-align: center;"><strong>Income (Standard Deviation)</strong></td>
<td style="text-align: center;"><strong>Reservation Income (Mean)</strong></td>
<td></td>
<td style="text-align: center;"><strong>Reservation Income (Standard Deviation)</strong></td>
<td style="text-align: center;"><strong>Experience (Mean)</strong></td>
<td></td>
<td style="text-align: center;"><strong>Experience</strong> <strong>(Standard Deviation)</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">Wage Aggregate</td>
<td style="text-align: center;">95992.73 (447)</td>
<td style="text-align: center;">133940.9</td>
<td style="text-align: center;">176173.7 (449)</td>
<td></td>
<td style="text-align: center;">181897.2</td>
<td style="text-align: center;">28.5432 (463)</td>
<td></td>
<td style="text-align: center;">36.63901</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Wage to Employer</td>
<td style="text-align: center;">97743.8 (121)</td>
<td style="text-align: center;">75351.02</td>
<td style="text-align: center;">176188.5 (122)</td>
<td></td>
<td style="text-align: center;">141697.3</td>
<td style="text-align: center;">29.18548 (124)</td>
<td></td>
<td style="text-align: center;">42.48584</td>
</tr>
<tr class="even">
<td style="text-align: center;">Wage to Self</td>
<td style="text-align: center;">68647.81 (137)</td>
<td style="text-align: center;">67612.87</td>
<td style="text-align: center;">146607.1 (140)</td>
<td></td>
<td style="text-align: center;">151669.7</td>
<td style="text-align: center;">21.8986 (143)</td>
<td></td>
<td style="text-align: center;">25.20476</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Stay in Wage</td>
<td style="text-align: center;">116440.7 (177)</td>
<td style="text-align: center;">190424.1</td>
<td style="text-align: center;">194609.2 (174)</td>
<td></td>
<td style="text-align: center;">212900.9</td>
<td style="text-align: center;">33. 67213 (183)</td>
<td></td>
<td style="text-align: center;">39.3755</td>
</tr>
</tbody>
</table>
<p><em>Source: authors’ computation from survey data<br>
Number of Observations in parentheses</em></p>
<p>Tabulating the characteristics of workers who are currently wage/salary employees (Table 3), we see that workers seeking to transition from wage/salary employment to employer status earn more than the average wage/salary employee while those seeking to transit to self-employment earn less than the average. We also see that workers planning to remain in wage-employment earn significantly more than the average wage-employed worker, which is a logical decision. The reservation income for workers’ seeking to transition from wage employment to employer status (176,000) is higher than that of those seeking to move to self-employment (147,000), signifying the consciousness of individuals seeking to transition to employer status of the need to pay staff. We also see that individuals seeking to transition to employer status have longer work experience periods (29 months) that those transitioning to self-employment (22 months). Workers planning to remain in wage-employment have worked for longer than the average wage/salary employee, which is further testament to their higher-than-average earnings.</p>
</section>
<section id="self-employed-workers-characteristics" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="self-employed-workers-characteristics"><span class="header-section-number">5.3</span> Self-employed workers characteristics</h2>
<table class="table">
<caption>Tabulation of currently self-employed worker’s statistics</caption>
<colgroup>
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 3%">
<col style="width: 13%">
<col style="width: 4%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th></th>
<th>SELF</th>
<th>EMPLOYMENT</th>
<th></th>
<th></th>
<th>STATISTICS</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>SELF EMPLOYMENT GROUPS</strong></td>
<td><strong>Income<br>
(Mean)</strong></td>
<td><strong>Income<br>
(Standard Deviation)</strong></td>
<td><strong>Reservation Income (Mean)</strong></td>
<td><strong>Reservation Income<br>
(Standard Deviation)</strong></td>
<td></td>
<td><strong>Experience (Mean)</strong></td>
<td></td>
<td><strong>Experience (Standard Deviation)</strong></td>
</tr>
<tr class="even">
<td>Self-Aggregate</td>
<td>127525.7 (175)</td>
<td>157908.2</td>
<td>211820.8<br>
(212)</td>
<td>342118.2</td>
<td></td>
<td>58.56477<br>
(193)</td>
<td></td>
<td>73.4332</td>
</tr>
<tr class="odd">
<td>Self to Wage</td>
<td>92741.94<br>
(31)</td>
<td>74574.78</td>
<td>148977.3<br>
(44)</td>
<td>127048.7</td>
<td></td>
<td>44.6129<br>
(31)</td>
<td></td>
<td>54.07876</td>
</tr>
<tr class="even">
<td>Self to Employer</td>
<td>81444.44<br>
(45)</td>
<td>57826.37</td>
<td>144347.8<br>
(46)</td>
<td>105042.9</td>
<td></td>
<td>48.59184<br>
(49)</td>
<td></td>
<td>54.22366</td>
</tr>
<tr class="odd">
<td>Stay in Self</td>
<td>165590.9<br>
(88)</td>
<td>204887.5</td>
<td>272009.1<br>
(110)</td>
<td>454919.9</td>
<td></td>
<td>63.83168<br>
(101)</td>
<td></td>
<td>78.39376</td>
</tr>
</tbody>
</table>
<p><em>Source: authors’ computation from survey data<br>
Number of Observations in parentheses</em></p>
<p>Tabulating the characteristics of workers who are currently in self-employment (Table 4), we see that workers seeking to transition from self-employment to wage-employment or employer status earn less than the average self-employed worker. We also see that workers planning to remain in self-employment earn significantly more than the average self-employed worker, which is a logical decision. The mean reservation income for workers’ seeking to transition from self-employment to wage-employment status (149,000) is lower than the average self-employed workers’ reservation income (212,000), but higher than that of those seeking to become employers (144,000). Similar to the wage-employment statistics, individuals seeking to transition to employer status have longer work experience periods (49 months) that those transitioning to wage-employment (45 months). Workers planning to remain in self-employment have worked for longer than the average self-employed individual, which is further testament to their higher-than-average earnings.</p>
</section>
<section id="workers-transition-statistics" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="workers-transition-statistics"><span class="header-section-number">5.4</span> Workers’ transition statistics</h2>
<table class="table">
<caption>Tabulation of worker’s current employment sector and educational level</caption>
<colgroup>
<col style="width: 32%">
<col style="width: 18%">
<col style="width: 27%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>CURRENT EMPLOYMENT SECTOR</th>
<th></th>
<th>INTENTIONS</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td><strong>SWITCH</strong></td>
<td><strong>NO SWITCH</strong></td>
<td><strong>TOTAL</strong></td>
</tr>
<tr class="even">
<td>Employer</td>
<td>4</td>
<td>49</td>
<td><strong>53</strong></td>
</tr>
<tr class="odd">
<td>Family Enterprise</td>
<td>28</td>
<td>9</td>
<td><strong>37</strong></td>
</tr>
<tr class="even">
<td>Self Employed</td>
<td>101</td>
<td>121</td>
<td><strong>222</strong></td>
</tr>
<tr class="odd">
<td>Wage/Salary Employee</td>
<td>273</td>
<td>183</td>
<td><strong>456</strong></td>
</tr>
<tr class="even">
<td>TOTAL</td>
<td><strong>406</strong></td>
<td><strong>362</strong></td>
<td><strong>768</strong></td>
</tr>
</tbody>
</table>
<p><em>Source: authors’ computation from survey data<br>
</em></p>
<p>Table 5 above depicts the employment transition intentions of workers captured during the survey exercise; we see that majority of workers plan to switch employment status in the next 5 years. Despite this fact, a sizeable number of workers also intend to remain in their current employment status in the next 5 years. Majority of workers who are currently wage/salary employed or work in family enterprise plan to switch employment sectors while the opposite holds true for workers who are currently self-employed or are employers as we see that a higher number of them plan to remain in self-employment and employer sector respectively.</p>
<div style="page-break-after: always;"></div>
<table class="table">
<caption>Tabulation of worker’s current and intended employment sector</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 12%">
<col style="width: 19%">
<col style="width: 16%">
<col style="width: 21%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>CURRENT EMPLOYMENT</th>
<th></th>
<th>STATUS</th>
<th>INTENDED</th>
<th>SWITCH</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td><strong>Employer</strong></td>
<td><strong>Family Enterprise</strong></td>
<td><strong>Self Employed</strong></td>
<td><strong>Wage/Salary Employee</strong></td>
<td><strong>TOTAL</strong></td>
</tr>
<tr class="even">
<td>Employer</td>
<td>49<br>
<em>(92.45)</em></td>
<td>0<br>
<em>(0.00)</em></td>
<td>3<br>
<em>(5.66)</em></td>
<td>1<br>
<em>(1.89)</em></td>
<td>53<br>
<em>100</em></td>
</tr>
<tr class="odd">
<td>Family Enterprise</td>
<td>12<br>
<em>(32.43)</em></td>
<td>9<br>
<em>(24.32)</em></td>
<td>8<br>
<em>(21.62)</em></td>
<td>8<br>
<em>(21.62)</em></td>
<td>37<br>
<em>100</em></td>
</tr>
<tr class="even">
<td>Self Employed</td>
<td>50<br>
<em>(22.52)</em></td>
<td>6<br>
<em>(2.70)</em></td>
<td>121<br>
<em>(54.50)</em></td>
<td>45<br>
<em>(20.27)</em></td>
<td>222<br>
<em>100</em></td>
</tr>
<tr class="odd">
<td>Unemployed</td>
<td>6<br>
<em>(13.64)</em></td>
<td>1<br>
<em>(2.27)</em></td>
<td>14<br>
<em>(31.82)</em></td>
<td>23<br>
<em>(52.27)</em></td>
<td>44<br>
<em>100</em></td>
</tr>
<tr class="even">
<td>Wage/Salary Employee</td>
<td>124<br>
<em>(27.19)</em></td>
<td>5<br>
<em>(1.10)</em></td>
<td>144<br>
<em>(31.58)</em></td>
<td>183<br>
<em>(40.13)</em></td>
<td>456<br>
<em>100</em></td>
</tr>
<tr class="odd">
<td>TOTAL</td>
<td>241<br>
<em>(29.68)</em></td>
<td>21<br>
<em>(2.59)</em></td>
<td>290<br>
<em>(35.71)</em></td>
<td>260<br>
<em>(32.02)</em></td>
<td>812<br>
<em>100</em></td>
</tr>
</tbody>
</table>
<p><em>Source: authors’ computation from survey data<br>
Percentages in parentheses</em></p>
<p>To take an understanding of the potential transition of workers to the next level, a tabulation of current employment sector against the intended sector was carried out. In preparing the tabulation, the intended employment sector of individuals who did not plan to switch employment sector in five years was filled with their current employment status. From table 6 above, we saw that workers who were currently employer plan to remain in this employment sector for the foreseeable future while majority of individuals who are family enterprise worker plan to transition to employer status (32.43 per cent). We also see from the table that majority of the individuals who are currently self-employed plan to remain in this employment status (54.50 per cent) while the second largest group of self-employed workers plan to transition to employer status (22.52 per cent). The third group of self-employed individuals plan to transition to wage employment (20.27) while the smallest group plan to transition to family enterprises (2.70). We can also deduce from the table that majority of individuals who are currently wage/salary employed plan to remain in this employment sector (31.58 per cent), the second largest group of individuals in this employment sector plan to switch to self-employment status (31.58), the third largest group plan to become employers in five years’ time (27.19) while the smallest group plan to transition into the family enterprise sector (1.10). It was also noted from the table that majority of individuals who are currently working under a family enterprise plan to switch employment sector to being an employer status (32.43per cent), while the second largest group plan to remain in the family enterprise (24.32). The remaining family enterprise workers equally want to switch to either self-employment or a wage/salary employment in five years’ time (21.62). Investigating the individuals who are currently unemployed, majority of these individuals wants to became a wage/salary employee (52.27 per cent), the second largest group wants to become self-employed (31.82). The third group of unemployed individuals want to become an employer (13.64 per cent) while the smallest group of unemployed individuals want to work with a family enterprise (2.27). The potential employment transition models will throw more light into the motivations for these desired future changes in employment status.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/figure2.png" class="img-fluid figure-img" alt="Source: authors’ computation from survey data"></p>
<figcaption class="figure-caption">Worker’s intended employment sectors and their motivations</figcaption>
</figure>
</div>
<p>characteristics of individual looking to switch employment status in five years’ time Figure1. It is observed that majority of workers plan to become employers in five years’ time with their major motivation being a need better room for growth and expansion. The second highest group of workers plan to become self-employed, their major motivation being a need for higher wage or income. The third group of workers plan to transition into wage-employment, their major reason for choosing this transition path also being the search for higher wage or income. The last group of workers plan to transition to family enterprise status but there wasn’t any discernable motivation for this switch as their motivations where evenly spread across all the options available in the questionnaire.</p>
</section>
<section id="evaluation-of-workers-parents-employment" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="evaluation-of-workers-parents-employment"><span class="header-section-number">5.5</span> Evaluation of workers’ parents’ employment</h2>
<p>Workers current employment against parents’ employment history</p>
<table class="table">
<caption>Tabulation of worker’s current employment sector and educational level</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 9%">
<col style="width: 2%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 2%">
<col style="width: 15%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>PARENTS’ EMPLOYMENT</th>
<th></th>
<th></th>
<th>CURRENT</th>
<th>EMPLOYMENT</th>
<th></th>
<th></th>
<th>STATUS</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td><strong>Employer</strong></td>
<td></td>
<td><strong>Family Enterprise</strong></td>
<td><strong>Self Employed</strong></td>
<td><strong>Unemployed</strong></td>
<td></td>
<td><strong>Wage/Salary Employee</strong></td>
<td><strong>TOTAL</strong></td>
</tr>
<tr class="even">
<td><strong>Employer</strong></td>
<td>3</td>
<td></td>
<td>1</td>
<td>14</td>
<td>2</td>
<td></td>
<td>23</td>
<td><strong>43</strong></td>
</tr>
<tr class="odd">
<td><strong>Family Enterprise</strong></td>
<td>18</td>
<td></td>
<td>22</td>
<td>19</td>
<td>6</td>
<td></td>
<td>63</td>
<td><strong>128</strong></td>
</tr>
<tr class="even">
<td><strong>Self Employed</strong></td>
<td>16</td>
<td></td>
<td>5</td>
<td>118</td>
<td>16</td>
<td></td>
<td>136</td>
<td><strong>219</strong></td>
</tr>
<tr class="odd">
<td><strong>Unemployed</strong></td>
<td>1</td>
<td></td>
<td>1</td>
<td>1</td>
<td>1</td>
<td></td>
<td>12</td>
<td><strong>16</strong></td>
</tr>
<tr class="even">
<td><strong>Wage/Salary Employee</strong></td>
<td>15</td>
<td></td>
<td>9</td>
<td>78</td>
<td>27</td>
<td></td>
<td>229</td>
<td><strong>358</strong></td>
</tr>
<tr class="odd">
<td><strong>TOTAL</strong></td>
<td><strong>53</strong></td>
<td></td>
<td><strong>38</strong></td>
<td><strong>230</strong></td>
<td><strong>52</strong></td>
<td></td>
<td><strong>463</strong></td>
<td><strong>836</strong></td>
</tr>
</tbody>
</table>
<p><em>Source: authors’ computation from survey data</em></p>
<p>Table 7 above shows us that there is no correlation between workers’ current employment status and the sector their parents worked or currently work. We see that a greater part of the labour force work in wage/salary employment regardless of their parent’s work history while the second largest group work in self-employment. The remainder of the labour force are spread evenly across Employer, Family enterprise and unemployment sectors.</p>
<table class="table">
<caption>Tabulation of workers’ parents employment sector against their intended employment sector</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 11%">
<col style="width: 18%">
<col style="width: 15%">
<col style="width: 20%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>PARENTS’ EMPLOYMENT</th>
<th></th>
<th>STATUS</th>
<th>INTENDED</th>
<th>SWITCH</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td><strong>Employer</strong></td>
<td><strong>Family Enterprise</strong></td>
<td><strong>Self Employed</strong></td>
<td><strong>Wage/Salary Employee</strong></td>
<td><strong>TOTAL</strong></td>
</tr>
<tr class="even">
<td><strong>Employer</strong></td>
<td>16</td>
<td>1</td>
<td>11</td>
<td>14</td>
<td><strong>42</strong></td>
</tr>
<tr class="odd">
<td><strong>Family Enterprise</strong></td>
<td>63</td>
<td>7</td>
<td>32</td>
<td>22</td>
<td><strong>124</strong></td>
</tr>
<tr class="even">
<td><strong>Self Employed</strong></td>
<td>67</td>
<td>5</td>
<td>129</td>
<td>78</td>
<td><strong>279</strong></td>
</tr>
<tr class="odd">
<td><strong>Wage/Salary Employee</strong></td>
<td>92</td>
<td>8</td>
<td>112</td>
<td>133</td>
<td><strong>345</strong></td>
</tr>
<tr class="even">
<td><strong>TOTAL</strong></td>
<td><strong>238</strong></td>
<td><strong>21</strong></td>
<td><strong>284</strong></td>
<td><strong>247</strong></td>
<td><strong>790</strong></td>
</tr>
</tbody>
</table>
<p><em>Source: authors’ computation from survey data</em></p>
<p>Evaluating workers’ intended employment status and that of their parents (Table 8), the findings are in line with literature as we see that workers who parents work or worked in wage employment, self-employment, and employer sector majorly have intentions to work in the same sectors. The exception is found in the family enterprise sector as majority of worker’s whose parents worked here would rather become employers, this choice to switch away from their parents’ employment status is seen to be as a result of a need for better room for growth and expansion which would be harder to obtain in a family enterprise as explained in the context of this paper.</p>
</section>
<section id="regression-results" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="regression-results"><span class="header-section-number">5.6</span> Regression results</h2>
<p><strong>Mincerian regression results</strong></p>
<p>The literature review has shown us that the major determinants of income, both locally and internationally, include age, sex, and educational level. The determinants of monthly income and reservation wage are further investigated with regression models using monthly income and reservation wage values from the survey. Regression results on the influence of various factors on workers’ monthly income and reservation wage are presented in table 5. The results for the monthly income model show that having longer employment durations (experience), higher monthly living costs, and possessing a national diploma or higher all significantly increase monthly income levels. We also see that working in non-wage employment (employers, self-employed, and family enterprise work) also led to increases in monthly income. As expected, we also see that being a female worker led to reductions in monthly income levels. Surprisingly, having apprenticeship experience also led to reductions in monthly income. From the monthly income model, we also notice that being married did not have a significant effect on monthly income. Moving on to the reservation wage model, we see from the results that unlike in the monthly income model, the only factors that led to increases in reservation wage expectations are monthly cost, possessing a Bachelor’s degree or higher, and being self-employed. From the results we also see that longer employment durations, possessing a national diploma or below, being married, working in a family enterprise, working as an employer, being a female worker, and having apprenticeship experience did not have a significant effect on reservation wage. We believe this is to be expected as respondents generally only considered their monthly living costs when asked the reservation wage expectation question. Regression models that explored interactions between variables such as sex, marital status, and educational level were explored, but it did not yield any noteworthy outcomes.</p>
<p>Table 9</p>
<table class="table">
<caption>Mincerian regression results</caption>
<colgroup>
<col style="width: 35%">
<col style="width: 21%">
<col style="width: 25%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>VARIABLES</th>
<th>Log Monthly Income</th>
<th>Log Reservation Income</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Employment duration</strong></td>
<td>0.00131***</td>
<td>0.000503</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>(-0.000429)</td>
<td>(-0.000422)</td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Log monthly cost</strong></td>
<td>0.671***</td>
<td>0.641***</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>(-0.0289)</td>
<td>(-0.0295)</td>
<td></td>
</tr>
<tr class="odd">
<td><strong>National diploma</strong></td>
<td>0.228***</td>
<td>0.00967</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>(-0.0581)</td>
<td>(-0.0568)</td>
<td></td>
</tr>
<tr class="odd">
<td><strong>BSc and above</strong></td>
<td>0.424***</td>
<td>0.280***</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>(-0.0515)</td>
<td>(-0.0501)</td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Married</strong></td>
<td>0.0342</td>
<td>-0.00812</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>(-0.0453)</td>
<td>(-0.0439)</td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Employer &amp; family enterprise</strong></td>
<td>0.241***</td>
<td>0.0607</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>(-0.0703)</td>
<td>(-0.0629)</td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Self employed</strong></td>
<td>0.213***</td>
<td>0.117**</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>(-0.0502)</td>
<td>(-0.0489)</td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Female</strong></td>
<td>-0.120***</td>
<td>-0.0705*</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>(-0.0435)</td>
<td>(-0.0418)</td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Apprenticeship experience</strong></td>
<td>-0.101**</td>
<td>0.0188</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>(-0.0411)</td>
<td>(-0.0397)</td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Constant</strong></td>
<td>3.429***</td>
<td>4.495***</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>(-0.307)</td>
<td>(-0.312)</td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Observations</strong></td>
<td>689</td>
<td>708</td>
<td></td>
</tr>
<tr class="even">
<td><strong>R-squared</strong></td>
<td>0.651</td>
<td>0.564</td>
<td></td>
</tr>
</tbody>
</table>
<p><em>Note: Standard errors in parentheses. *** p&lt;0.01, ** p&lt;0.05, * p&lt;0.1<br>
Source: authors’ computation from survey data<br>
Other variables considered in the regression include; Age</em></p>
<div style="page-break-after: always;"></div>
<p><strong>Potential employment transition results</strong></p>
<p>Multinomial logit models have been used to assess the likelihood of employment transition in a wide range of studies ( <span class="citation" data-cites="guven2018">Guven-Lisaniler, Tuna, and Nwaka (<a href="#ref-guven2018" role="doc-biblioref">2018</a>)</span>; <span class="citation" data-cites="taiwo2013">Taiwo (<a href="#ref-taiwo2013" role="doc-biblioref">2013</a>)</span>). Using a multinomial logit model, the potential transition of workers from wage employment or self-employment, to other employment sectors was analysed by examining factors that could influence the probability of transitioning from one employment sector to another. The potential employment transitions that were focused on are; wage employment to self-employment, wage employment to employer status, self-employment to wage-employment, and self-employment to employer status. The base categories for the two transition models are those workers who chose to remain in wage/salary employment and self-employment respectively. For the wage to employer transition, we see that being married had a negative impact on the probability of this employment sector transition while having apprenticeship experience increased the likelihood of this transition occurring. For the wage/salary employment to self-employment transition, we see that larger childhood household sizes increased the probability of this transition occurring</p>
<table class="table">
<caption>Employment sector transition regression results</caption>
<colgroup>
<col style="width: 30%">
<col style="width: 18%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>VARIABLES</th>
<th>WAGE TO EMPLOYER</th>
<th>WAGE TO SELF</th>
<th>SELF TO WAGE</th>
<th>SELF TO EMPLOYER</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Childhood household</td>
<td>0.0139</td>
<td>0.0600**</td>
<td>-0.07</td>
<td>-0.105**</td>
</tr>
<tr class="even">
<td></td>
<td>(-0.0304)</td>
<td>(-0.0297)</td>
<td>(-0.0536)</td>
<td>(-0.0505)</td>
</tr>
<tr class="odd">
<td>Employment duration</td>
<td>-0.000453</td>
<td>-0.00365</td>
<td>0.000386</td>
<td>-5.76E-05</td>
</tr>
<tr class="even">
<td></td>
<td>(-0.00363)</td>
<td>(-0.00435)</td>
<td>(-0.00453)</td>
<td>(-0.00389)</td>
</tr>
<tr class="odd">
<td>Log wage premium</td>
<td>0.0408</td>
<td>-0.129</td>
<td>-0.336</td>
<td>-0.184</td>
</tr>
<tr class="even">
<td></td>
<td>(-0.166)</td>
<td>(-0.162)</td>
<td>(-0.345)</td>
<td>(-0.279)</td>
</tr>
<tr class="odd">
<td>Log monthly income</td>
<td>0.219</td>
<td>-0.362</td>
<td>-0.958*</td>
<td>-0.827*</td>
</tr>
<tr class="even">
<td></td>
<td>(-0.239)</td>
<td>(-0.246)</td>
<td>(-0.51)</td>
<td>(-0.429)</td>
</tr>
<tr class="odd">
<td>Married</td>
<td>-0.674**</td>
<td>-0.907***</td>
<td>-0.0657</td>
<td>0.0885</td>
</tr>
<tr class="even">
<td></td>
<td>(-0.289)</td>
<td>(-0.29)</td>
<td>(-0.663)</td>
<td>(-0.532)</td>
</tr>
<tr class="odd">
<td>Apprenticeship experience</td>
<td>0.630**</td>
<td>0.486*</td>
<td>1.188**</td>
<td>0.704</td>
</tr>
<tr class="even">
<td></td>
<td>(-0.262)</td>
<td>(-0.258)</td>
<td>(-0.602)</td>
<td>(-0.48)</td>
</tr>
<tr class="odd">
<td>National diploma</td>
<td>-0.0794</td>
<td>-0.737*</td>
<td>0.0111</td>
<td>-0.501</td>
</tr>
<tr class="even">
<td></td>
<td>(-0.404)</td>
<td>(-0.412)</td>
<td>(-0.707)</td>
<td>(-0.635)</td>
</tr>
<tr class="odd">
<td>BSc &amp; above</td>
<td>-0.209</td>
<td>-0.0391</td>
<td>0.377</td>
<td>0.333</td>
</tr>
<tr class="even">
<td></td>
<td>(-0.393)</td>
<td>(-0.368)</td>
<td>(-0.692)</td>
<td>(-0.575)</td>
</tr>
<tr class="odd">
<td>Parent’s non-wage employment</td>
<td>0.392</td>
<td>0.517**</td>
<td>-0.0774</td>
<td>-0.293</td>
</tr>
<tr class="even">
<td></td>
<td>(-0.262)</td>
<td>(-0.258)</td>
<td>(-0.598)</td>
<td>(-0.49)</td>
</tr>
<tr class="odd">
<td>Female</td>
<td>-0.114</td>
<td>0.37</td>
<td>-1.061</td>
<td>-0.496</td>
</tr>
<tr class="even">
<td></td>
<td>(-0.271)</td>
<td>(-0.26)</td>
<td>(-0.72)</td>
<td>(-0.548)</td>
</tr>
<tr class="odd">
<td>Constant</td>
<td>-3.464</td>
<td>4.546*</td>
<td>13.36***</td>
<td>11.53***</td>
</tr>
<tr class="even">
<td></td>
<td>(-2.553)</td>
<td>(-2.669)</td>
<td>(-5.034)</td>
<td>(-4.223)</td>
</tr>
<tr class="odd">
<td>Observations</td>
<td>401</td>
<td>401</td>
<td>134</td>
<td>134</td>
</tr>
</tbody>
</table>
<p><em>Note: Standard errors in parentheses. *** p&lt;0.01, ** p&lt;0.05, * p&lt;0.1</em> <em>Source: authors’ computation from survey data</em></p>
<p>We also see that the probability of transitioning from wage/salary employment to self-employment was also negatively impacted by being married. Here, having parents that currently or previously worked in non-wage employment significantly increased the probability of this transition occurring. Having apprenticeship experience also played significant but minor role in the likelihood of this transition occurring. For the self-employment to wage/salary employment transition, monthly income and reservation wage has a minor impact of the probability of this transition occurring, other variables considered did not have significant effects on this employment sector transition. For the self-employment to employer transition, having larger childhood household sizes positively influenced the likelihood of this transition occurring, monthly income also had a significant but minor effect on the possibility of this transition occurring.</p>
</section>
</section>
<section id="conclusion-and-policy-recommendations" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Conclusion and policy recommendations</h1>
<p>In this study, we undertook a comprehensive analysis of Nigerian workers prospective employment sector preferences by examining motivations, monthly income levels, reservation wage expectations, and factors determining transition across employment sectors. The study utilized data from a multidisciplinary survey carried out <strong>Helpman Development Institute (HDI) Garki II, Abuja</strong> from October 9th to October 24th 2023 that sought to gather data on employment sector (labour) choices, current wage/income levels, reservation wage expectations, fertility choices, and insurance knowledge. For this paper, data was mostly drawn from the background and labour section of the questionnaire. The descriptive analysis indicates a significant proportion of workers aspire to become employers, driven by the desire for a better room for growth and expansion. The remaining workers plan to transition to self-employment or wage employment, primarily motivated by the pursuit of higher wage/income. We also see that majority of workers have intentions to work in their parents’ former or current employment sector with the only exception being found in the family enterprise sector. The tabulation of current employment sector against intended sector showed that apart from the family enterprise workers, workers in the other employment sectors planned to remain there in five years’ time. Narrowing down, the next largest group of wage and self-employed workers that plan to transition to other employment sectors chose to move to self-employment and employer status respectively. From the monthly income and reservation wage summary statistics showed us that Self-employed individuals, on average, earned more than their wage-employed counterparts, reflecting the autonomy and potential income benefits associated with self-employment. From the summary statistics of the potential employment transitions of wage and self-employed workers, we see that with those aspiring to move from wage employment to employer status exhibit higher reservation wages than those seeking self-employment, which could be in recognition of the need to pay staff. Wage and self- employed workers that plan to remain in their current employment sector earn higher monthly income on the average than those seeking to transition away, explaining their comfort in staying their respective employment sectors. The Mincerian regression results show us that employment duration, possessing a national diploma or higher, and working in non-wage employment have strong positive effects on monthly income. From the reservation wage model, the only factor that had a strong significant effect was monthly cost. From the wage transition model, workers transitioning to employer status, the likelihood of being married and apprenticeship experience emerged as the only significant variables. On the other hand, for those transitioning to self-employment, childhood household, married status, and parents’ non-wage employment were found to be significant factors. This implies that individuals with larger family childhood household sizes, married individuals, and those whose parents are engaged in non-wage employment are more inclined to pursue self-employment. Furthermore, the self-employment transition model sheds light on some factors influencing transitions from self-employment to wage employment or employer sector. The identified significant variables offer valuable insights into the factors shaping these transitions. For workers transitioning from self-employment to wage employment, having apprenticeship experience was the major positive determinant of this transition path while for individuals moving from self-employment to employer status, having larger childhood households emerged as the only crucial positive determinant of this employment transition. A major policy recommendation comes from the fact that results show us that majority of the individuals seeking to transition plan move to either employer or self-employment sector, their major motivation being in search for better room for growth and expansion. Therefore, the creation of structures that support the growth and expansion of businesses will help in easing this transition process, thus leading to economic growth.</p>
<div style="page-break-after: always;"></div>
<p><strong>Reference</strong></p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-aminu2016" class="csl-entry" role="listitem">
Aminu, Alarudeen. <span>“Determinants of Participation and Earnings in Wage Employment in Nigeria.”</span>
</div>
<div id="ref-duncan1989" class="csl-entry" role="listitem">
Duncan, Greg J., and Daniel H. Hill. 1989. <span>“Assessing the Quality of Household Panel Data: The Case of the Panel Study of Income Dynamics.”</span> <em>Journal of Business &amp; Economic Statistics</em> 7 (4): 441–52. <a href="https://doi.org/10.1080/07350015.1989.10509756">https://doi.org/10.1080/07350015.1989.10509756</a>.
</div>
<div id="ref-fields2011" class="csl-entry" role="listitem">
Fields, Gary S. 2011. <span>“Labor Market Analysis for Developing Countries.”</span> <em>Labour Economics</em> 18: S16–22.
</div>
<div id="ref-folawewo2020" class="csl-entry" role="listitem">
Folawewo, Abiodun Oluwole, and Olusegun A Orija. 2020. <span>“Informal-Formal Workers’ Transition in Nigeria: A Livelihood Analysis.”</span> WIDER Working Paper.
</div>
<div id="ref-garofalo2016" class="csl-entry" role="listitem">
Garofalo, Antonio, Massimiliano Agovino, et al. 2016. <span>“The Impact of Education on the Determination of the Wage Differential Between Workers in the South and Centre-North Italy.”</span> <em>PANOECONOMICUS</em>.
</div>
<div id="ref-gupta1984" class="csl-entry" role="listitem">
Gupta, Manash Ranjan. 1984. <span>“Migration, Unemployment and Development: A Dynamic Two-Sector Analysis.”</span> <em>Economics Letters</em> 16 (1-2): 177–84.
</div>
<div id="ref-guven2018" class="csl-entry" role="listitem">
Guven-Lisaniler, Fatma, Gulcay Tuna, and Ikechukwu Darlington Nwaka. 2018. <span>“Sectoral Choices and Wage Differences Among Nigerian Public, Private and Self-Employees.”</span> <em>International Journal of Manpower</em> 39 (1): 2–24.
</div>
<div id="ref-ikechukwu2016" class="csl-entry" role="listitem">
Ikechukwu Darlington, Nwaka. 2016. <span>“Heterogeneity in the Nigerian Labour Market: Exploring the Wage Gap.”</span>
</div>
<div id="ref-jimohsocial" class="csl-entry" role="listitem">
Jimoh, Adams Lukman. n.d. <span>“Social-Demographic Factors and Wage Determination.”</span>
</div>
<div id="ref-kawaguchi2007" class="csl-entry" role="listitem">
Kawaguchi, Daiji, and Ken Yamada. 2007. <span>“The Impact of the Minimum Wage on Female Employment in Japan.”</span> <em>Contemporary Economic Policy</em> 25 (1): 107–18.
</div>
<div id="ref-krumboltz1976" class="csl-entry" role="listitem">
Krumboltz, John D, Anita M Mitchell, and G Brian Jones. 1976. <span>“A Social Learning Theory of Career Selection.”</span> <em>The Counseling Psychologist</em> 6 (1): 71–81.
</div>
<div id="ref-olaposi2014" class="csl-entry" role="listitem">
Olaposi, TO, CM Adelowo, and SO Akintelu. 2014. <span>“FACTORS INFLUENCING TRANSITION TO SELF-EMPLOYMENT FROM ORGANIZATIONAL EMPLOYMENT.”</span> <em>Asian Journal of Business and Economics</em> 4 (4.4).
</div>
<div id="ref-poole1998" class="csl-entry" role="listitem">
Poole, Michael, and Glenville Jenkins. <span>“Human Resource Management and the Theory of Rewards: Evidence from a National Survey.”</span>
</div>
<div id="ref-samahiya2023" class="csl-entry" role="listitem">
Samahiya, Obrein Muine, and Ebenezer Lemven Wirba. 2023. <span>“Returns to Education and Wage Inequality in Namibia.”</span>
</div>
<div id="ref-taiwo2013" class="csl-entry" role="listitem">
Taiwo, Olumide. 2013. <span>“Employment Choice and Mobility in Multi-Sector Labour Markets: Theoretical Model and Evidence from Ghana.”</span> <em>International Labour Review</em> 152 (3-4): 469–92.
</div>
<div id="ref-thurow1975" class="csl-entry" role="listitem">
Thurow, Lester C. 1975. <span>“Equity Concepts and the World of Work.”</span> <em>American Behavioral Scientist</em> 18 (3): 387–99.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>